### ISSUE TITLE
Sort Performance Data for Checks

### ISSUE THREAD

**Issue by oxzi** [Icinga/icingadb-web#1007]
## Is your feature request related to a problem? Please describe.

The performance data returned from executed check commands is listed in the order as written from the check plugin. When the check plugin uses some "non-deterministic" data structure - like a map/hash map/dict - to create those performance entries, the order of the performance data changes for each run. This will be reflected in Icinga DB Web, making it hard to compare performance metrics.

To reproduce and understand this, I created an unholy check plugin which rotates the order of its performance data entries.

```sh
#!/usr/bin/env bash
echo -n 'tja|'
echo -e ''\''foo'\''='$((1+$RANDOM%1000))';500;750\n'\''bar'\''='$((1+$RANDOM%1000))';500;750\n'\''buz'\''='$((1+$RANDOM%1000))';500;750' | shuf | tr '\n' ' '
exit $(($RANDOM%4))
```

When creating service objects, the entries in the Performance Data view in Icinga Web 2 is sorted differently.

<details>
<summary>Screenshots from Icinga Web 2</summary>

In Icinga DB Web, this might look like the following:
![2024-04-10-140936_1534x1419_scrot](https://github.com/Icinga/icingadb-web/assets/8402811/4f62b90a-60c9-4fe6-9244-5dc5b23c3536)
![2024-04-10-140931_1534x1419_scrot](https://github.com/Icinga/icingadb-web/assets/8402811/54aee285-ee12-4ff9-9e1e-4b79aeaa90b0)
![2024-04-10-140926_1534x1419_scrot](https://github.com/Icinga/icingadb-web/assets/8402811/d98cc4a5-7dd8-4860-99b0-1f985be30a82)
</details>

## Describe the solution you'd like

I would like to see the performance data points to be sorted, e.g., alphabetically.

## Describe alternatives you've considered

Of course, this issue could be solved in the check plugin itself. However, I would generally like the idea of having a sorted list.

**Comment by nilmerg** [comment]
> e.g., alphabetically.

I guess some strongly oppose against this. Some plugins use a meaningful order, some don't. We cannot differentiate that and destroy the order of those which do.

So I'd say, this is **very** unlikely to change.

**Comment by oxzi** [comment]
![https://xkcd.com/1172/](https://imgs.xkcd.com/comics/workflow.png)

Fair enough. Thus, I'll try to address the issue at its root or introduce a meta check which alters the output.
