### ISSUE TITLE
Permission to see contacts/users

### ISSUE THREAD

**Issue by chrnie** [Icinga/icingadb-web#1013]
## Is your feature request related to a problem? Please describe.
In the ido "monitoring" module it was possible to deny the permission to see contacts to icingaweb users.

## Describe the solution you'd like
It would be nice to have this possibility again

## Additional context
In the monitoring module it's called:
no-monitoring/contacts: Prohibit access to contacts and contactgroups

ref/NC/769621

**Comment by nilmerg** [comment]
https://icinga.com/docs/icinga-db-web/latest/doc/04-Security/#denylists

**Comment by nilmerg** [comment]
And: https://icinga.com/docs/icinga-db-web/latest/doc/10-Migration/#permissions

**Comment by chrnie** [comment]
thanks a lot, works like charm
