### ISSUE TITLE
Plugin Output limits limit too much

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icingadb-web#1017]
## Describe the bug
The changes introduced in #998 limit the Plugin Output to 10.000 symbols (chars?) by default,
which, in some edge cases is not enough ( ref NC/817322 ).

## Possible solution
Add a configuration parameter (config.ini) to set the limit manually for a setup.

**Comment by nilmerg** [comment]
It's now performed the same way as in the monitoring module, which wasn't a problem for years.

What is meant with *is not enough*? What's the exact edge case? The ticket reference is useless for anyone not having access, so don't leave out such vital details due to this.

**Comment by RincewindsHat** [comment]
Well, in this case there is some output which has close to 250 000 characters. And someone wants/needs to see it.
Apparently this was not a problem with the monitoring module, but why that should be the case if the limit is the same, I can not say.

**Comment by markuslf** [comment]
> It's now performed the same way as in the monitoring module, which wasn't a problem for years.
> 
> What is meant with _is not enough_? What's the exact edge case? The ticket reference is useless for anyone not having access, so don't leave out such vital details due to this.

Maybe it worked for years in the past, but plugins are constantly evolving, checking more and more complex scenarios, and in some (rare) cases (sometimes) need more than 10k output, especially for debugging purposes where Icinga is the first source of truth.
