### ISSUE TITLE
Min/Max/Warning/Critical field values show "None" in the "Performance Data" table

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icingadb-web#1024]
Hello

There are 2 Icinga servers.
On an old server with the classic Icinga Web interface, the data in the Performance Data table is displayed correctly:

![изображение](https://github.com/Icinga/icingadb-web/assets/17614847/07971062-0062-4d7a-a519-c89f5df93d2b)

On the new server with Icinga DB Web, the data in the Performance Data table is not completely displayed. The Min, Max, Warning, Critical fields are always displayed as "None":

![изображение](https://github.com/Icinga/icingadb-web/assets/17614847/ecf535a7-99c8-4f06-a86e-2412bad6e54d)

Although we know for sure that the perfdata contains information about thresholds:

![изображение](https://github.com/Icinga/icingadb-web/assets/17614847/d5208cd3-eb43-4825-8f8f-466002321f84)

## Expected behavior

We expect to see data in the Min, Max, Warning, Critical fields in the Performance Data table

## Environment

* Icinga DB Web version (System - About): 1.1.2
* Icinga Web 2 version (System - About): 2.12.1
* Web browser: Firefox ESR 102 / MS Edge 124 / Google Chrome 120
* Icinga 2 version (`icinga2 --version`): r2.14.2-1
* Icinga DB version (`icingadb --version`): 1.2.0
* PHP version used (`php --version`): 8.2.18
* Server operating system and version: Debian Bookworn 12.5

**Comment by nilmerg** [comment]
Hi,

in the source tab, there is also a row called "normalized_performance_data". Please show that as well.

**Comment by Aleksey-Maksimov** [comment]
![изображение](https://github.com/Icinga/icingadb-web/assets/17614847/320615eb-b02b-493d-bb6f-36ac5dc99e72)

**Comment by nilmerg** [comment]
Thanks. Though, this seems to be related to https://github.com/Icinga/icinga2/issues/9038. So Icinga DB Web can't do much about this, sorry. Please leave a comment there.

**Comment by Aleksey-Maksimov** [comment]
Sorry. I don't quite understand the essence of the problem. Maybe there is a workaround? Previously, we did not have this problem on the old installation of Icinga Web 2 + IDO

**Comment by nilmerg** [comment]
Icinga DB Web relies on how Icinga 2 (Icinga DB) processes performance data. The monitoring module (IDO) does not. That is why such a limitation now also affects Web.
