### ISSUE TITLE
Initial Dashboard option to change view info=level

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingadb-web#1025]
## Is your feature request related to a problem? Please describe.
In the initial Dashboard you can't set the view info level the dashboard is hardcoded to view=minimal

/usr/share/icingaweb2/modules/icingadb/configuration.php

```
        /**
         * Current Incidents
         */
        $dashboard = $this->dashboard(N_('Current Incidents'), ['priority' => 50]);
        $dashboard->add(
            N_('Service Problems'),
            'icingadb/services?service.state.is_problem=y'
            . '&view=minimal&limit=32&sort=service.state.severity desc',
            100
        );
        $dashboard->add(
            N_('Recently Recovered Services'),
            'icingadb/services?service.state.soft_state=0'
            . '&view=minimal&limit=32&sort=service.state.last_state_change desc',
            110
        );
        $dashboard->add(
            N_('Host Problems'),
            'icingadb/hosts?host.state.is_problem=y'
            . '&view=minimal&limit=32&sort=host.state.severity desc',
            120
        );

```

## Describe the solution you'd like
It would be user friendly to give them the choice of what info level would be useable .. like in the other Host/Service Dashlets.  

![Screenshot](https://github.com/Icinga/icingadb-web/assets/7203835/e6ed4400-98b2-4fda-b0c5-fb6507038b85)

**Comment by nilmerg** [comment]
Users have the choice to remove these from their dashboard and replace them with their own version. The dashboard doesn't have any controls, besides this, so it's not possible for Icinga DB Web to add the view mode switcher there.
