### ISSUE TITLE
Redundant titles

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#104]
We should avoid redundant titles wherever possible. e.g. in the host detail view the `Services` and `Host Group` titles are such a case.

![Screenshot from 2020-06-15 08-53-19](https://user-images.githubusercontent.com/16668527/84626718-e91da780-aee5-11ea-97d8-8483d1b8d92e.png)

**Comment by flourish86** [comment]
What do you think about unifying both sections and titling it »Relations«.

**Comment by nilmerg** [comment]
Unifying them, yes. Labeling them *Relations*.. mhm, not wrong, but I would have get used to it.

**Comment by flourish86** [comment]
> Unifying them, yes. Labeling them _Relations_.. 

🙏🏻

> mhm, not wrong, but I would have get used to it.

I see your point. But I couldn't come up with anything better as well.

**Comment by lippserd** [comment]
I'm not entirely happy with _Relations_ either.

We could drop the `HorizontalKeyValue` widget here and display the content directly under the appropriate headings.

# Host Detail

![10 211 55 9_icingaweb2_icingadb_services (1)](https://user-images.githubusercontent.com/1894563/90394681-61921780-e093-11ea-98cc-cdf691422bf5.png)

## Service Detail

![10 211 55 9_icingaweb2_icingadb_services](https://user-images.githubusercontent.com/1894563/90394696-6951bc00-e093-11ea-850f-dfc7b8709396.png)

**Comment by nilmerg** [comment]
@lippserd I could maybe befriend me with this solution for the services widget. But the hostgroups are shown as badges, and all other badges have their sub-title on the left (users, usergroups) so isn't this inconsistent?

**Comment by lippserd** [comment]
> @lippserd I could maybe befriend me with this solution for the services widget. But the hostgroups are shown as badges, and all other badges have their sub-title on the left (users, usergroups) so isn't this inconsistent?

I see. What do you think of the following solution?

* Remove Notifications heading
* Introduce heading for users
* Introduce heading for user groups
* We no longer need to have subtitles

**Comment by nilmerg** [comment]
That's way too pragmatic that I even considered suggesting this :joy:

**Comment by nilmerg** [comment]
We'll just remove the sub-titles as shown in Eric's first post.
