### ISSUE TITLE
Add a detail view for redundancy groups

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#1056]
With #1050, redundancy groups are listed as part of an object's root problems. They're not clickable yet, though.

## Routing

The detail is accessible through `icingadb/redundancygroup` requiring the parameter `id` and the hex-formatted id of the group as value.

## The View

![Screenshot from 2024-10-29 09-23-16](https://github.com/user-attachments/assets/9719acf2-df35-47f0-a4b4-e56a6d4b4781)

## Click Paths

* Root problem items representing redundancy groups provide a link to this view
* "List all…" links to a new tab

**Comment by sukhwinder33445** [comment]
The detail view should contain the following details:

- **Quick Actions**: Same as in Service/Host case.
- **Collapsible plugin output**: Output of the handled member or member with the worst severity, depending on what influences the redundancy group.
-  An `RedundancyGroupDetailExtension` Hook
