### ISSUE TITLE
Graphite graphs are not shown with disabled monitoring-module

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#108]
## Describe the bug
If the monitoring-module is disabled, the graphs provided via graphite-module are not shown any more.

## Screenshots
![graphite-graphs](https://user-images.githubusercontent.com/3973350/87302952-9948f500-c512-11ea-9c02-0dda2e09cc18.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0.-rc1
* Graphite Module: 1.1.0
* Icinga Web 2 version (System - About): 2.8.1
* Web browser: Chrome
* Icinga 2 version (`icinga2 --version`): 2.12.0-rc1
* Icinga DB version (`icingadb --version`): 1.0.0-rc1
* PHP version used (`php --version`): 7.3.11
* Server operating system and version: CentOS 7.8.2003

**Comment by m4k5ym** [comment]
I explore the same issue but with latest Debian based OS and latest Firefox.

I also have to disable the map module before I was able to see anything in the icingadb-web module but that something different. 

In my particular setup I even don't see the graphs section at all.

**Comment by drapiti** [comment]
This is true also for grafana graphs not only Graphite.

**Comment by nilmerg** [comment]
That's due to the modules themselves. They're expecting that a host/service is from the IDO, not Icinga DB and hence can't access it if the monitoring module is disabled. This will change once there is proper support for Icinga DB in those modules.
