### ISSUE TITLE
Filter in tactical view gives different results for Icing IDO Web and Icinga DB Web

### ISSUE THREAD

**Issue by johannesst** [Icinga/icingadb-web#1092]
## Describe the bug
Using the same filter conditions in the tactical overview yield different results in the IDO-based IcingaWeb and IcingaDB Web frontends.

## To Reproduce

1. Open IcingaIDO tactical overview and specify a filter:
![image](https://github.com/user-attachments/assets/8c82248e-eee6-4fe9-96d1-00306d183694)
2. Open IcingaDB tactical overview and enter the same conditions: 
![image](https://github.com/user-attachments/assets/4644e49a-9aa1-4fa3-82ce-9952f8fe0a33)
3. Open IcingaDB tactical overview and specify a filter with !~ instead of !=;
![image](https://github.com/user-attachments/assets/7e947f4c-69ed-4152-aac7-d643314f6128)
As you can see the tactical overview in IcingaDB gives different service and hosts counts compared to IcingaIDO. 

## Expected behavior
One of the filters should return the same amount of hosts and services like with Icigna IDO. 

## Your Environment

![image](https://github.com/user-attachments/assets/194fc1d8-57b7-42aa-b695-f3ebb4f1d503)
* Icinga DB Web version (System - About):  1.1.3
* Icinga Web 2 version (System - About): 2.12.1 
* Web browser: Google Chrome Version 130.0.6723.117 (Offizieller Build) (64-Bit) Windows 10 22H2 Build 19045.5011

* Icinga 2 version (`icinga2 --version`): r2.14.3-1
* Icinga DB version (`icingadb --version`): Icinga DB version: v1.2.0
* Icinga Redis (`icinga-redis-server --version`): icingadb-redis-server --version
Redis server v=7.2.6 sha=4e7416a9:0 malloc=jemalloc-5.3.0 bits=64 build=fec6fb8a9e0b305c
* PHP version used (`php --version`): PHP 8.1.2-1ubuntu2.19 (cli) (built: Sep 30 2024 16:25:25) (NTS)
* Server operating system and version: Ubuntu 22.04.5 LTS, 5.15.0-125-generic #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## Additional context
The Icinga cluster was initially set up with two master nodes and one mariadb database five years ago. I added IcingaDB yesterday, both frontends are now running parallel.
Following modules are used at the moment:
![image](https://github.com/user-attachments/assets/191c2cbb-ebeb-493b-826a-355cf5f1b6a0)
And following feature are used:
sudo icinga2 feature list
Disabled features: compatlog debuglog elasticsearch gelf graphite influxdb2 journald livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command icingadb ido-mysql influxdb mainlog notification

## Remarks

Maybe I'm missing something is there any documentation of the new filter format? I tried to look it up in the docs or with googling but to no avail. If there is anything I can do to help with debugging or testing I'm happy to help

**Comment by nilmerg** [comment]
> specify a filter with !~ instead of !=;

This is the intended solution. I also don't see a notable difference in the screenshots 1 and 3.

> Maybe I'm missing something is there any documentation of the new filter format?

Yes. [Here](https://icinga.com/docs/icinga-db-web/latest/doc/05-Upgrading/#upgrading-to-icinga-db-web-v11).

**Comment by johannesst** [comment]
Thanks for the reply.  Due to more pressing matters I didn't looked this up  so I couldn't checked this earlier. 
So sorry for the delay. 

> > specify a filter with !~ instead of !=;
> 
> This is the intended solution. I also don't see a notable difference in the screenshots 1 and 3.

Like in this screenshot from today the number of Hosts doesn't match (the number of services do though):
![image](https://github.com/user-attachments/assets/5dd739bc-7064-456b-8521-697ea99d9cdc)

I'm fine if the filter behaviour changed in that regard, but I would  prefer to have this mentioned in the documentation. 
The linked Upgrade notes doesn't mention this though.

**Comment by nilmerg** [comment]
> The linked Upgrade notes doesn't mention this though.

They do??

> **Breaking Changes**
> We’ve extended our filter syntax to include new signs for like and unlike comparisons. These are ~ and !~, respectively. The equal (=) and unequal (!=) operators won’t perform any wildcard matching anymore due to this.
