### ISSUE TITLE
Quick actions container exceed column -> unnecessary horizontal scroll bars

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#110]
## Describe the bug
Detail views have unnecessary horizontal scrolling.

## To Reproduce
1) Open the detail view of any host or service of the icingadb-web module.
2) scroll horizontally

## Screenshots
![Screenshot 2020-07-14 at 15 14 28](https://user-images.githubusercontent.com/6977434/87433035-1cd51580-c5e9-11ea-86b1-9d4cac0a6414.png)

## Your Environment
At least Safari, Chrome, Firefox

**Comment by nilmerg** [comment]
Can't reproduce with Chrome and Firefox, please check again and close here if it's the same for you.

**Comment by flourish86** [comment]
Since this has become obsolete, I'll close.
