### ISSUE TITLE
ServiceList: Clicking on host makes service item active

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#115]
## Describe the bug

When clicking the host on a service list item the item (which represents a service) will become "active". This is wrong since this results in the host detail view to appear.

## To Reproduce

1. Go to a service list
2. Click the host name in the item's title

## Expected behavior

Two options:
1) The service list item should not be shown as active
2) In the legacy monitoring module there was always a host tab in services. This could be re-introduced and after a click on the host name could be activated instead. This would be the preferred version

## Screenshots

![Screenshot 2020-08-04 at 16 08 45](https://user-images.githubusercontent.com/6977434/89303844-03b20880-d66d-11ea-80f1-6bac5fd4b71e.png)

## Your Environment

![Screenshot 2020-08-04 at 16 10 51](https://user-images.githubusercontent.com/6977434/89303901-188e9c00-d66d-11ea-9869-0aed082c517f.png)

**Comment by nilmerg** [comment]
I'd opt for #2

**Comment by nilmerg** [comment]
@lippserd Any objections?

**Comment by lippserd** [comment]
> @lippserd Any objections?

Nope, go for it!
