### ISSUE TITLE
Object inspection like in the director

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingadb-web#117]
## Is your feature request related to a problem? Please describe.
For the "inspect" button you need to install director, this should be a feature of icingaweb2 and not director. Some user dont want to use and maintain director package just for this feature

## Describe the solution you'd like
Inspect feature is part of icingaweb2 and not director only

**Comment by nilmerg** [comment]
Yep, the upvotes speak for themselves, we'll consider this for sure!
