### ISSUE TITLE
Multiple right Data type gives an error

### ISSUE THREAD

**Issue by pmloei** [Icinga/icingadb-web#119]
Multiple right data types gives an error, the wrong not.

## 1. Reproduce error:
1. Create hosts.conf in custom.conf.d directory.
2. Set variable notes_url and action_url as a string, described like in the docs.
3. Restart Icinga web and see the error in the host.
![fehlerfall1](https://user-images.githubusercontent.com/43344523/90406270-36182880-e0a5-11ea-9558-b31ee59fc56a.png)

## 2. Expected error in this case:
1. Create hosts.conf in custom.connf.d directory.
2. Set variable notes_url as a string inside an array, not like in the docs.
![fotomitErfolg1](https://user-images.githubusercontent.com/43344523/90406144-079a4d80-e0a5-11ea-90bc-71537f4307af.png)

## 3. Expected behavior:
Expected no error with the multiple data type string.
![fehlerfallmit1](https://user-images.githubusercontent.com/43344523/90406192-15e86980-e0a5-11ea-84b1-07e49cf18438.png)  

Expected an error with an array, for example on notes_url, meaning using wrong data type.
![fehlerMit3](https://user-images.githubusercontent.com/43344523/90408010-85f7ef00-e0a7-11ea-96f0-9d1003ebc520.png)

## 4. Environment

- Icinga DB Web version : 1.0.0-rc1
- Icinga Web 2 version : 2.8.1
- Web browser : Chrome
- Icinga 2 version : r2.12.0-rc1-1
- Icinga DB version : v1.0.0-rc1
- PHP version used : 7.4.8
- Server operating system and version : ubuntu 18.04

**Comment by nilmerg** [comment]
This would have been tremendously more obvious if you included the actual error here. Please do so now if you don't mind.

**Comment by pmloei** [comment]
Comment edited

**Comment by pmloei** [comment]
Issue solution in pull request : #122

**Comment by nilmerg** [comment]
Please don't close issues manually. An issue is only solved if the associated PR is merged, which then closes the issue automatically.
