### ISSUE TITLE
Search overview display

### ISSUE THREAD

**Issue by arcadesolutions** [Icinga/icingadb-web#125]
## Describe the bug
The "Search"overview seems to handle the first host and service incorrectly

## To Reproduce
Just search for a host/service

## Expected behavior
Should be on the same entry as the rest

## Screenshots
![image](https://user-images.githubusercontent.com/8624321/92454514-df43d180-f1c0-11ea-8693-7afb922a3827.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc1
* Icinga Web 2 version (System - About): 2.8.2
* Web browser: Chrome 84.0.4147.135
* Icinga 2 version (`icinga2 --version`): 2.12.0-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc1
* PHP version used (`php --version`): 7.1.26
* Server operating system and version: CentOS 7.5.1804

**Comment by Al2Klimov** [comment]
Hello @arcadesolutions and thank you for reporting!

Please tell you browser tab size in pixels.

Best,
AK

**Comment by nilmerg** [comment]
@Al2Klimov We don't need any feedback here. And never do we need any info on the amount of pixels to investigate such an issue. That's due to how we handle reduced layout requests in dashlets and should be fixed in master while also using Icinga Web 2 2.8+.

**Comment by claudiospizzi** [comment]
Same issue here, but found a workaround by adding the following css style:

```css
.icinga-module > .controls { overflow: auto; }
.icinga-module > .controls::-webkit-scrollbar { display: none; }
```
