### ISSUE TITLE
be compatible with default themes

### ISSUE THREAD

**Issue by fireba11** [Icinga/icingadb-web#126]
The module should produce nice views with all of icingaweb2s default color schemes.
Currently you can't see much with dark theme especially.

**Comment by nilmerg** [comment]
Hi,

just looked at all themes. The colorblind theme is quite low on contrast, but all the other themes look okay to me. So does also the solarized-dark theme.

Please show some screenshots of the issues you have with the themes.

**Comment by nilmerg** [comment]
I see, that's the case with the v1.0.0-rc1 release only. In the current master this section looks fine:

![Screenshot from 2020-10-14 08-37-31](https://user-images.githubusercontent.com/16668527/95952652-cb5f4100-0df8-11eb-9a6a-edf9e26c94fb.png)

So this is a bug that's already fixed. Thanks for reporting though!
