### ISSUE TITLE
Compact View: Fix view mode switcher height

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#131]
## Describe the bug

List view's View Mode Switcher is too tall in compact view.

## Suggestion

Maybe adjust icon size(?)

## Screenshots
![Screenshot 2020-10-19 at 17 38 15](https://user-images.githubusercontent.com/6977434/96475024-d02a5780-1233-11eb-92ff-cb0ad33f1291.png)

**Comment by nilmerg** [comment]
Should be re-evaluated as part of #182
