### ISSUE TITLE
Comment/Downtime List: Remove object names in detail view

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#135]
## Describe the bug
Object names in list item titles are redundant in detail view

## Suggestion
Remove said parts in detail view.

## Screenshots
![Screenshot 2020-10-19 at 18 08 54](https://user-images.githubusercontent.com/6977434/96476991-3f08b000-1236-11eb-9ee7-862647b6a57f.png)

**Comment by nilmerg** [comment]
Solved as part of #184
