### ISSUE TITLE
Horizontal scroll bars in detail view

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#137]
## Describe the bug
The detail view seems to have exceeding elements. So, there's scroll bars appearing.

## Screenshots
![Screenshot 2020-10-19 at 18 14 43](https://user-images.githubusercontent.com/6977434/96477780-306ec880-1237-11eb-8a08-f08befd5cb5f.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by nilmerg** [comment]
Duplicate of #110 ?

**Comment by flourish86** [comment]
> Duplicate of #110 ?

No, it's a different issue. #110 was only the quick actions container scrolling, but it seems to be solved already.

**Comment by nilmerg** [comment]
If not, I can't reproduce this either. Can you still?

**Comment by flourish86** [comment]
> If not, I can't reproduce this either. Can you still?

No.
