### ISSUE TITLE
Replace default icons for Icinga DB Index

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#139]
## Describe the bug
Menu items still have the default icon on the Icinga DB Nav Index Page

## Screenshots
![Screenshot 2020-10-19 at 18 21 33](https://user-images.githubusercontent.com/6977434/96478412-f0f4ac00-1237-11eb-94da-1f3597a625e3.png)

**Comment by nilmerg** [comment]
Duplicate of #59
