### ISSUE TITLE
Downtime List: Provide additional information in detailed view mode

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#143]
## Describe the bug
There's no difference in display, when switching between view mode default and detailed.

## Expected behavior
There should be additional information in detailed view mode, like multiline comment text in the caption or alternatively no detailed view mode.

### Current Default view mode

![Screen Shot 2020-10-20 at 15 26 15](https://user-images.githubusercontent.com/6977434/96592674-ee05c400-12e8-11eb-9e32-de00e3ea351a.png)

### Detailed view mode

![Screen Shot 2020-10-20 at 15 26 09](https://user-images.githubusercontent.com/6977434/96592703-f78f2c00-12e8-11eb-8315-87c5814b81e5.png)

**Comment by flourish86** [comment]
I wondered at first, because currently the downtime list items show 2 lines of caption in the default view.

The screenshots only show one, so I guess, that it was intended that way originally. Was this an intentional change?

I think it would look more balanced with only one. Also the visual would align perfectly with the lower height.

This is the current version (ignore the crazy data)

![Screen Shot 2021-05-12 at 10 53 29](https://user-images.githubusercontent.com/6977434/117947420-780e8c00-b310-11eb-82ee-4d9db98879a6.png)

**Comment by nilmerg** [comment]
That's probably a side-effect of the clean-up I made in #184. Though, the elllipsis looks fine on my end:

![Screenshot from 2021-05-12 11-16-25](https://user-images.githubusercontent.com/16668527/117950639-ae99d600-b313-11eb-99ab-5e640fdabddf.png)

**Comment by nilmerg** [comment]
Oh, ehm, and I don't see why downtimes should not behave the same as other lists with comments/output. (regarding the 2 lines)

**Comment by flourish86** [comment]
This can be closed, right?

**Comment by nilmerg** [comment]
Seems so
