### ISSUE TITLE
Add tool tips for controls

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#144]
## Describe the bug
It's hard to guess what not labeled control elements will do.

## Expected behavior
Unlabeled control elements should have a title attribute, so that there's an explanation of what they will do.

View Switcher, something like
* Show compact list items
* Show default list item information
* Show detailed list item information

Sort direction button:
* Sort list items in an ascending order
* Sort list items in an descending order

Since the other list item control elements are labeled, title attributes might only be necessary for accessibility reasons.

**Comment by nilmerg** [comment]
Thanks Ravi!
