### ISSUE TITLE
The documentation links are all broken

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#175]
## Describe the bug
I just cloned the repo and wanted to look something up in the documentation but I always get 404 as a response back.

## To Reproduce
Just click on one of the links under Documentation, Istallation, Configuration or Migration.

## Expected behavior
Should be redirected to the correct page.

## Screenshots

<img width="1379" alt="Bildschirmfoto 2021-03-23 um 10 47 23" src="https://user-images.githubusercontent.com/57616252/112126980-45c09800-8bc5-11eb-937b-bb920a732a94.png">

**Comment by nilmerg** [comment]
That's on icinga.com. So this issue should be there where that's handled. Though, I don't think we have a Github repo for this, or do we? @bobapple

**Comment by nilmerg** [comment]
Ping @bobapple

**Comment by bobapple** [comment]
Fixed it, sorry for the delay! 🙈
