### ISSUE TITLE
Filter on "Custom Variables"

### ISSUE THREAD

**Issue by kmjonsson** [Icinga/icingadb-web#180]
## Is your feature request related to a problem? Please describe.
In icingaweb2/monitoring it's possible to filter on custom variables on host/services.
This is not possible in icingadb web. This is usefull for custom searches on the fly without making a host/servicegroup.

## Describe the solution you'd like
The same feature as in icingaweb2

It would be nice if searching in arrays as well. We have a list of "tags" for our hosts that we use in icinga and other places to group hosts.

**Comment by nilmerg** [comment]
Hi,

this **is** indeed possible. What have you tried that you came to that conclusion?

**Comment by kmjonsson** [comment]
I'm using the 1.0.0rc1 icingadb with icinga2 2.13.3-1.focal and icingaweb2 2.8.2-1.focal on Ubuntu.

In the filter dropdown on for example "hosts" I don't have any of my custom vars that I have if I the normal icingaweb2 interface.

I have for an simple example an host.vars.os = "Linux" on my linux machines. This is the output from icingaweb2 & icingadb web:
![icingadb](https://user-images.githubusercontent.com/5999662/114053540-53497380-988f-11eb-93ab-e8f176fd8979.png)
![icingaweb2](https://user-images.githubusercontent.com/5999662/114053542-53e20a00-988f-11eb-915e-b1f6e31db27b.png)

**Comment by nilmerg** [comment]
Ah, i see. You should try the current master. The RC is way too old. It's currently a not so user-friendly installation though, please read [this forum post](https://community.icinga.com/t/error-accessing-icingadb-module-in-icingaweb-configuration/6977) for more info. If you have problems with the installation, don't hesitate to ask for help in the forum as well.
