### ISSUE TITLE
Collapsible controls

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#185]
Since we have a separation line between controls and content, there's a visual mis-match if multiple columns with differently sized controls are shown simultaneously.

![Screenshot from 2021-04-23 10-23-26](https://user-images.githubusercontent.com/16668527/115842982-a8a08b80-a41e-11eb-95ad-f78250d58cbc.png)

There are already the following issues which also highlight the problem:

* Fix Downtime Detail Header Design #141
* Align control elements #132
* List Controls break line #130
* Make control container height match #133

## The Problem

I also see the visual mis-match, but I don't think this is a battle we can win. We can of course define strict heights and row separations in controls, but this way we highly limit ourselves in a way which controls we can show there. It's also nearly impossible to make this match on every screen size. The risk that this will never be fixed entirely is high and we probably fix it once, twice, a third time and then a new feature/module appears and it's broken again.

So to me this is a question of cost/effort vs. benefits and not any of the proposed solutions in the linked issues are viable.

## The Solution?

Let's grant ourselves the freedom of (nearly) doing whatever we want in controls and ignore the not aligned separation lines. :joy: I'd be fine with this, as I'm not too bothered by this *issue* and don't think of it as a sign of quality.

If that's not an option, I'd suggest to give the controls a rather low `min-height` (so that it's effectively only a single line) and only show selected controls (TBD) always. Other controls need to be expanded, in a way. We talked about this already if I correctly remember.

--

@lippserd, @flourish86 please give your thoughts on the matter.

**Comment by lippserd** [comment]
For me it's a sign of quality 😆  I really think we should be able to align our controls.

**Comment by nilmerg** [comment]
Fine, then it's your job. :man_shrugging:

**Comment by nilmerg** [comment]
## The Compromise?

![Screenshot from 2021-04-26 12-10-40](https://user-images.githubusercontent.com/16668527/116066958-f0c2e680-a688-11eb-945b-fd55ab9aba0a.png)

**Comment by flourish86** [comment]
Sorry, but it seems, like I don't get the point, to be honest.

The matching height in the screenshot is fine. But the filter input is still too tall and the alignment with the actions in the detail controls is still off.

**Comment by nilmerg** [comment]
This isn't about the controls itself, just about the separation line...

**Comment by flourish86** [comment]
> This isn't about the controls itself, just about the separation line...

Ah, the change wasn't clear to me.

It's a lazy work around and won't address the aesthetic issue @lippserd pointed out (which I support). I don't like it, but that doesn't mean, we cannot do it.

Deciding if we care about these kind of things in general would be helpful for future issues.
