### ISSUE TITLE
Missing event detail views

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#188]
There are detail views for events in the monitoring module. Here they're missing.

![Screenshot from 2021-04-26 14-12-15](https://user-images.githubusercontent.com/16668527/116080497-7189de80-a699-11eb-9588-f396a59bea80.png)

**Comment by nilmerg** [comment]
@flourish86 Do we have mockups for these somewhere? Could you make some if not?

**Comment by flourish86** [comment]
We don't have event details for history items in icingadb-web at the moment, do we?

**Comment by nilmerg** [comment]
No, that's the reason this issue exists?...
