### ISSUE TITLE
Cleanup namespaces

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#189]
* [x] `Icinga\Module\Icingadb\Widget\DowntimeList` vs `Icinga\Module\Icingadb\Widget\ItemList\CommentList`
* [x] `Icinga\Module\Icingadb\Widget\BaseListItem` vs `Icinga\Module\Icingadb\Common\BaseListItem`
* [x] `Icinga\Module\Icingadb\Widget\BaseItemList` vs `Icinga\Module\Icingadb\Common\BaseItemList`
* [x] `Icinga\Module\Icingadb\Widget\DowntimeList` vs `Icinga\Module\Icingadb\Widget\ItemList\DowntimeList`
* [x] `Icinga\Module\Icingadb\Widget\DowntimeListItem` vs `Icinga\Module\Icingadb\Widget\ItemList\DowntimeListItem`
* [x] `Icinga\Module\Icingadb\Widget\HostListItem` vs `Icinga\Module\Icingadb\Widget\ItemList\HostListItem`
* [x] `Icinga\Module\Icingadb\Widget\HostList` vs `Icinga\Module\Icingadb\Widget\ItemList\HostList`
* [x] `Icinga\Module\Icingadb\Widget\HostListItemDetailed` vs `Icinga\Module\Icingadb\Widget\ItemList\HostListItemDetailed`
* [x] `Icinga\Module\Icingadb\Widget\HostListItemMinimal` vs `Icinga\Module\Icingadb\Widget\ItemList\HostListItemMinimal`
* [x] `Icinga\Module\Icingadb\Widget\HostListItemDetailed` vs `Icinga\Module\Icingadb\Widget\ItemList\HostListItemDetailed`
* [x] `Icinga\Module\Icingadb\Widget\Card` vs `ipl\Web\Widget\Card`
* [x] ~~`Icinga\Module\Icingadb\Widget\Health` vs `ipl\Web\Widget\Health`~~
* [x] `Icinga\Module\Icingadb\Widget\HorizontalKeyValue` vs `ipl\Web\Widget\HorizontalKeyValue`
* [x] `Icinga\Module\Icingadb\Widget\VerticalKeyValue` vs `ipl\Web\Widget\VerticalKeyValue`
* [x] ~~`Icinga\Module\Icingadb\Widget\ShowMore` vs `ipl\Web\Widget\ShowMore`~~
* [x] `Icinga\Module\Icingadb\Widget\TimeAgo` vs `ipl\Web\Widget\TimeAgo`
* [x] `Icinga\Module\Icingadb\Widget\TimeSince` vs `ipl\Web\Widget\TimeSince`
* [x] `Icinga\Module\Icingadb\Widget\TimeUntil` vs `ipl\Web\Widget\TimeUntil`
* [x] ~~`Icinga\Module\Icingadb\Widget\TagList` vs `ipl\Web\Widget\TagList`~~
* [x] `Icinga\Module\Icingadb\Widget\ViewModeSwitcher` vs `Icinga\Module\Icingadb\Web\Control\ViewModeSwitcher`
* [x] `Icinga\Module\Icingadb\Widget\PerfDataTable` vs `Icinga\Module\Icingadb\Widget\Detail\PerfDataTable`

**Comment by sukhwinder33445** [comment]
I have only looked at the classes in 'icingadb-web/library/Icingadb/Widget' for now. Are there also classes elsewhere that should be sorted? 

I would change the namespaces as shown above in comment. Please give your opinion @nilmerg ?

**Comment by nilmerg** [comment]
> Icinga\Module\Icingadb\Widget\Card vs ipl\Web\Widget\Card

This widget is abstract, so it shouldn't directly reside in the widget namespace.

> Icinga\Module\Icingadb\Widget\Health vs ipl\Web\Widget\Health

This widget is not generic enough for being in ipl-web.

> The following looks like a widget to me as well (move to ipl-web?):

Nope. The markdown stuff requires a class of Icinga Web 2 and the base status bar not generic enough.

> Icinga\Module\Icingadb\Widget\HostStateBadges vs Icinga\Module\Icingadb\Widget\Host\HostStateBadges
> Icinga\Module\Icingadb\Widget\ServiceStateBadges vs Icinga\Module\Icingadb\Widget\Service\ServiceStateBadges

If we'd already have these namespaces I'd agree. We don't so I don't :)

> Icinga\Module\Icingadb\Widget\CheckAttempt vs Icinga\Module\Icingadb\Widget\Common\CheckAttempt

The common namespace is for non-concrete stuff, traits, interfaces and abstract classes.
I'd rather move `MarkdownLine` and `MarkdownText` for exact this reason out of this namespace.
