### ISSUE TITLE
User custom vars should be displayed

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingadb-web#19]
https://github.com/Icinga/icingaweb2/issues/4070

@N-o-X mentioned that the new schema makes it possible to display the custom vars, so we might want to do that! :)

**Comment by nilmerg** [comment]
The same applies to hostgroups, servicegroups and usergroups.

**Comment by nilmerg** [comment]
We'll show customvars for users and user-groups just like for hosts/services. In the case of user-groups though, we'll also limit the amount of users shown to 6 and show a "Show More" link if there are more.
