### ISSUE TITLE
Downtime Detail Progress Widget: Timeline exceeds viewport

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#190]
## Describe the bug
I found this, though I find it hard to tackle down, how to recreate this. Maybe it's because the downtime parameters somehow happened to be odd.

The "Now" marker is way behind the endtime, so the column viewport heavily exceeding the viewport.

## Screenshots

![Screen Shot 2021-04-29 at 09 25 20](https://user-images.githubusercontent.com/6977434/116516049-65866280-a8cd-11eb-9bab-c8cc78d52317.png)

![Screen Shot 2021-04-29 at 09 24 53](https://user-images.githubusercontent.com/6977434/116516060-6919e980-a8cd-11eb-9288-648875cbc5ba.png)

**Comment by nilmerg** [comment]
Start and end time is bugged here. This is an issue with Icinga DB to me, not a layout issue.

**Comment by flourish86** [comment]
Ok. Just wanted to keep it stored somewhere, after I discovered it. Then I'll close again.
