### ISSUE TITLE
[host|service].is_acknowledged filter does not work

### ISSUE THREAD

**Issue by afletch** [Icinga/icingadb-web#191]
## Describe the bug
`host.is_acknowledged` or `service.is_acknowledged` when specified as 'y' do not return acknowledged hosts or services, or exclude acknowledged hosts and services when specified as 'n'. All hosts/service problems are returned with 'n' and none are returned with 'y'.

## To Reproduce
example:
icingadb/hosts?host.state.is_problem=y&host.state.is_acknowledged=n&modifyFilter=1
or
icingadb/services?service.state.is_acknowledged=y&modifyFilter=1

1. generate host + service problems
2. ack the host and service problems
3. use the filters to try and view only the acked service and host problems
4.

## Expected behavior
acked host problems _only_ should appear with `host.is_acknowledged=y`
acked service problems _only_ should appear with `service.is_acknowledged=y`
acked host problems should _not_ appear with `host.is_acknowledged=n`
acked service problems  should _not_ appear with `service.is_acknowledged=n`

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc1
* Icinga Web 2 version (System - About):     2.8.2
* Web browser: n/a
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Icinga DB version (`icingadb --version`): v1.0.0-rc1
* PHP version used (`php --version`): 7.3.20
* Server operating system and version: CentOS Linux release 7.9.2009

**Comment by nilmerg** [comment]
Hi,

this may have been due to some bugs in the RC1 only. Since then, we've changed many things and a RC2 is due soon. Please check this then out once more, and open a new issue if the issue comes up again. Thank you!
