### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by mzac** [Icinga/icingadb-web#194]
## Describe the bug
Installing icingadb-web on two systems and getting the same error.  Tested on Redhad and Ubuntu.  All the dependencies are installed.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. clone the repo for icingaweb-db
2. try to click on the module
3. get error

## Expected behavior
It should not have an error

## Screenshots
```
Undefined offset: 1

#0 /usr/share/php/Icinga/Application/Modules/Module.php(891): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/php/Icinga/Application/Modules/Module.php(841): Icinga\Application\Modules\Module->metadata()
#2 /usr/share/icingaweb2/application/views/scripts/config/module.phtml(9): Icinga\Application\Modules\Module->getDependencies()
#3 /usr/share/php/Icinga/Web/View.php(248): include(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): master branch
* Icinga Web 2 version (System - About): 2.8.2
* Web browser: Chome 90
* Icinga 2 version (`icinga2 --version`): r2.12.3-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc1
* PHP version used (`php --version`): 7.4.3
* Server operating system and version: Ubuntu 20.04 and Redhat 7

**Comment by nilmerg** [comment]
Hi, the master of Icinga DB Web is not supported by Icinga Web v2.8.2. You should also use the master of Icinga Web 2.
