### ISSUE TITLE
Unecessary wide text spacing in list item titles

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#213]
## Describe the bug

![Screen Shot 2021-06-15 at 15 11 09](https://user-images.githubusercontent.com/6977434/122058770-421b6680-cdec-11eb-8f4c-238f79397059.png)

![Screen Shot 2021-06-15 at 15 11 58](https://user-images.githubusercontent.com/6977434/122058778-434c9380-cdec-11eb-8b4d-0e5559be13d2.png)

**Comment by nilmerg** [comment]
I don't see a problem on the service list, it's exactly one char width (a space) there.

The downtime list looks indeed weird, but I never liked the colon there. I'd remove that and be done with this.
