### ISSUE TITLE
Search input field

### ISSUE THREAD

**Issue by sir-max** [Icinga/icingadb-web#219]
I am a heavy user of the search input field top left. But when I disable the monitoring module and use icingadb only, the search field ist gone. I wonder if this is a bug or just missing?

![image](https://user-images.githubusercontent.com/48131143/123230225-4e33b200-d4d7-11eb-9f71-3610ecab9656.png)

**Comment by nilmerg** [comment]
This is fixed since #50.

**Comment by sir-max** [comment]
Thank you, did not pull the lates state, only the release. It is indeed fixed now. Thank you
