### ISSUE TITLE
The command transport Form doesn't seem quite correct

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#220]
## Describe the bug
IMHO, the command transporter form does not look to be correct compared to the one from Monitoring Module. It lacks descriptions for a few inputs and also a form title. Besides, the validate button is also still missing.

<img width="844" alt="Bildschirmfoto 2021-06-28 um 15 33 31" src="https://user-images.githubusercontent.com/57616252/123645000-35eccb80-d826-11eb-92fa-6018a1f5bc85.png">

**Comment by nilmerg** [comment]
That's all intentionally.

* Descriptions are not required if the label suffices
* A form title isn't required, there's a tab
* The validate button was always a psychological thing (the form validates anyway before saving anything), and hence wasn't preserved here
