### ISSUE TITLE
Fix search editor opener button alignment 

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#238]
This is how the alignment of `.search-editor-opener` button looks correctly aligned in the hosts list

![Screen Shot 2021-08-16 at 17 08 25](https://user-images.githubusercontent.com/6977434/129586089-b7f3fd6d-321a-4736-953d-942a63f6a19a.png)

Since the user group list is lacking the "continue with" feature the button is missing. Hence, the `.search-editor-opener` button is misaligned.

![Screen Shot 2021-08-16 at 17 08 15](https://user-images.githubusercontent.com/6977434/129586093-d5080b1a-31af-4c13-a8df-f7d0b6bbca04.png)

Current Master

**Comment by nilmerg** [comment]
I bet you can come up with a better issue title :wink:
