### ISSUE TITLE
Undefined array key "downtime"

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#241]
## Describe the bug
Just freshly pulled my `icingadb-web` and seeing this error message when i press on the `Downtimes` Icinga DB subitems.

<img width="1428" alt="Bildschirmfoto 2021-08-18 um 17 33 33" src="https://user-images.githubusercontent.com/57616252/129927428-02a1a622-7ab3-40f2-9668-5b946f03fcbe.png">

**Comment by nilmerg** [comment]
Make sure you've upgraded ipl-orm as well and have the icingadb database schema updated.

**Comment by Yonas-net** [comment]
Thanks!
