### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#248]
## Describe the bug
As this [PR](https://github.com/Icinga/icingadb-web/pull/218) was created before this 262a17598c520ee294d7592ab3925bd6d4c3b129 commit was being merged, unfortunately there is now problems because the signature of `Controller::createViewModeSwitcher()` method has been changed.

<img width="1252" alt="Bildschirmfoto 2021-08-20 um 16 36 51" src="https://user-images.githubusercontent.com/57616252/130249957-575729ce-a6e2-4b2f-a889-d5fb04ac60ed.png">

**Comment by Yonas-net** [comment]
Please see also in `NotificationsController`.

**Comment by nilmerg** [comment]
FYI: I've merged a related change for `NotificationsController` just now to master.
