### ISSUE TITLE
Downtime cannot be scheduled because of Validation Error (Safari only)

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#255]
## Describe the bug
A clear and concise description of what the issue is.

## To Reproduce

1. Open Host or Service Detail in Safari
2. Click Schedule Downtime Action
3. Enter Comment
4. Submit form by clicking "Schedule" button

## Expected behavior
Validation should work and the Downtime should be scheduled (see correct behavior in Chrome/FF)

## Screenshots
![Screen Shot 2021-08-23 at 14 34 09](https://user-images.githubusercontent.com/6977434/130448469-d9816c34-424b-41fb-aaec-fcda7ed1243f.png)

**Comment by nilmerg** [comment]
Does it work in the monitoring module?

**Comment by flourish86** [comment]
Yes. Also I've recognized, that it doesn't use our own time picker, but the native one on both. (in Safari)

![Screen Shot 2021-08-23 at 15 58 59](https://user-images.githubusercontent.com/6977434/130460302-2e88e056-8956-4156-aa46-af831c6bee01.png)

**Comment by nilmerg** [comment]
> Also I've recognized, that it doesn't use our own time picker, but the native one on both.

That's intentional.

**Comment by flourish86** [comment]
It also occurs for "Reschedule Check".
