### ISSUE TITLE
Optimize scheduling source alignment

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#256]
![Screen Shot 2021-08-23 at 16 19 18](https://user-images.githubusercontent.com/6977434/130463437-2e5a18d9-3df4-4487-a6b4-13ae54fb9f81.png)

**Comment by nilmerg** [comment]
Please include what to optimize.

**Comment by flourish86** [comment]
`.key` and `.value` should either be aligned to baseline (1) or we should use the same `font-size`s as in the custom vars table (2).

Also the colon (:) can be left out, since key and value are differentiated by font style.


This would solve option (1):

```
.icinga-module.module-icingadb .check-statistics .card-footer .key {
  …
  align-self: baseline;
  line-height: calc(1/.83333333 * 1.5);
}
```

**Comment by nilmerg** [comment]
The font-sizes follow the same rules as the vertical-key-value widgets. It's just a horizontal-key-value now.

The colon cannot be left out. It's a structural element, not a style element. And style is not structural. In the downtime list items we also didn't just remove the colon but replaced it with a semantically correct conjunction (`for`).

**Comment by flourish86** [comment]
The titles for downtimes is something completely different, because list item titles are meant to be full sentences.

This looks perfect to me.

![Screen Shot 2021-08-30 at 16 02 20](https://user-images.githubusercontent.com/6977434/131351547-e2d4c8ba-eae1-43f1-bba0-e11bab638c05.png)

**Comment by nilmerg** [comment]
> because list item titles are meant to be full sentences.

And that is this exactly not, a full sentence, hence the colon.
