### ISSUE TITLE
Make view mode global per view only

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#260]
## Describe the bug
When switching the view mode in the `host services`, the switcher in `hosts` list is also switched, however, it has no effect on the list, as the `Paginator` and the `default limit` aren't updated.

**Comment by nilmerg** [comment]
Before working on this we should discuss whether it even makes sense to update the view mode in in an unrelated *visible* view. Emphasis on **visible**.

**Comment by Yonas-net** [comment]
Not sure 🤔 why it is working now, but the defaultLimit is being recalculated correctly.

**Comment by Yonas-net** [comment]
Even the Paginator works perfectly too, if you wait till the autorefresh is triggered.

**Comment by nilmerg** [comment]
As discussed: The view mode should not be global for every view, but only global *per* view.
