### ISSUE TITLE
Downtime progress bar has different heights

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#263]
## Describe the bug
The downtimes have different heights for the progress bar and there is no space between the visuals.

## Screenshot

![Screenshot 2021-08-24 at 13 22 53](https://user-images.githubusercontent.com/54990055/130614045-95024073-176f-4d4d-a6b7-667176fca947.png)

## Reproduce
Add some downtimes to a host/service.

**Comment by nilmerg** [comment]
Please include the browser used with such reports.

**Comment by sukhwinder33445** [comment]
I have tested this with `Safari`, `Chrome` and `Firefox`. This bug only occurs in Chrome.

**Comment by Yonas-net** [comment]
Can confirm this.

<img width="1268" alt="Bildschirmfoto 2021-08-24 um 14 48 52" src="https://user-images.githubusercontent.com/57616252/130619017-66f2b880-f36e-41b7-8c36-1d543a83fc51.png">

**Comment by flourish86** [comment]
> I have tested this with `Safari`, `Chrome` and `Firefox`. This bug only occurs in `Chrome`.

Is it dependent on the zoom level?

**Comment by sukhwinder33445** [comment]
> Is it dependent on the zoom level?

Oh yes. I had zoom `90%` as default and it leads to this problem (on Safari, Firefox, Chrome). Zoom 100% works fine.

**Comment by sukhwinder33445** [comment]
According to @flourish86 this is not really a bug. Browser zoom 100% and most others like 75% or 110% work fine.

**Comment by flourish86** [comment]
Actually this seems to me like rounding errors with `em` occurring.

Browsers‘ zoom rendering gets better with this but they act pretty unpredictably, especially with `em`s. 

I think the only option to have that reliably consistent is to use `px` and that is not an option.

**Comment by nilmerg** [comment]
> I think the only option to have that reliably consistent is to use px and that is not an option.

Why not? We use pixels for small sizes anyway (e.g. for borders), so why not here as well?

**Comment by flourish86** [comment]
> Why not?

It won't adapt to layout changes. 1px makes sense because it won't get smaller anyway.

Everything above doesn't in my opinion, but if you think we should, I'd be perfectly fine with that.

**Comment by nilmerg** [comment]
It's just a difference of a single pixel.. Sometimes such things can be decided by case and here I'd opt for pixels. I already prepared the changes in #377. It does look okay to me in all different layout modes. There's only weird gap between the item's border and the progress bar on high zoom levels.
