### ISSUE TITLE
Improve PDF layout

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#266]
## Describe the bug
Exported PDFs look bad.

## Expected behavior
Exported PDFs look good.

## Screenshots
[hosts-index-1629811546.pdf](https://github.com/Icinga/icingadb-web/files/7039486/hosts-index-1629811546.pdf)

**Comment by Yonas-net** [comment]
How did you even get that to work? I only get the following error message. `This route does not support the requested output format`

**Comment by nilmerg** [comment]
I've worked around that error. :grin: PDF export technically works, it's just the error that prevents it.

**Comment by Yonas-net** [comment]
The result is still not perfect, I think 🤔.
[Host-2021-08-31 18_02_38.pdf](https://github.com/Icinga/icingadb-web/files/7085296/Host-2021-08-31.18_02_38.pdf)
[Hosts-2021-08-31 18_03_39.pdf](https://github.com/Icinga/icingadb-web/files/7085302/Hosts-2021-08-31.18_03_39.pdf)

**Comment by nilmerg** [comment]
Hah, I didn't test with Icinga Web 2 master but only with v2.9.3. That's an issue because the dark theme is applied to pdf exports. Please open an issue at the pdfexport module asking for the light theme to be applied instead.
