### ISSUE TITLE
Don't allow users to remove scheduled downtime objects

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#269]
## Describe the bug
Trying to remove a scheduled downtime object shows an error that this isn't possible.

## Expected behavior
If it's not possible to remove the downtime, we should disable the removal button with an indication why it's disabled.

## Additional context
https://github.com/Icinga/icingadb/issues/231

**Comment by Yonas-net** [comment]
This can be easily determined once this [PR](https://github.com/Icinga/icingadb/pull/301) has been merged.
