### ISSUE TITLE
Object Detail: "Remove Ack…" icon spins, when clicked

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#271]
## Describe the bug
The after clicking the 'trash' icon spins. This looks awkward.

## To Reproduce

1. Open an acknowledged object's detail view
2. click the "remove acknowledgement" icon

## Expected behavior
The `.spinner` related styles of the icon spinning should be removed

## Screenshots

![Screen Shot 2021-08-24 at 16 06 57](https://user-images.githubusercontent.com/6977434/130631472-57494165-f8e2-4784-92e6-763e304da123.png)

## To Dos

- [x] Globally Replace `.spinner` icon with a generic loading icon after submit
- [x] ~~Show success notification for toggling ack state~~ (#272)

**Comment by nilmerg** [comment]
We have to indicate progress somehow. If the icon being spinned looks bad, we should try to show an icon that looks good if spinned.

**Comment by Yonas-net** [comment]
Is it also intentional that we don't show any notification at all when an ACK is deleted?

**Comment by flourish86** [comment]
> We have to indicate progress somehow. If the icon being spinned looks bad, we should try to show an icon that looks good if spinned.

Yes, totally agree. Let's have the icon replaced by a generic loading icon for the `.spinner` element, so we won't have this problem sneak in in the future.

**Comment by flourish86** [comment]
> Is it also intentional that we don't show any notification at all when an ACK is deleted/created?
> 
> **notification** => **Success** message.

The button changing after submitting the modal dialogue indicates that already. But having a notification would be even better.

**Comment by nilmerg** [comment]
> The button changing after submitting the modal dialogue indicates that already. But having a notification would be even better.

Didn't we want to reduce superfluous notifications?

**Comment by flourish86** [comment]
> > I'm not sure, to be honest.
> 
> It was your suggestion! 🤷‍♂️

If that's the case, then it was either not thought out or I failed to communicate it clearly.

For the user it is not transparent, if they use a form or a link, when clicking a button and they shouldn't have to worry about it.

Therefore there should be a consistent status notification after every action (success or error). Since we don't have that (e.g. Ack reloads view, vs. Notification doesn't give any feedback at all), we should use notifications for all of them.

Otherwise – without looking actively for a confirmation in a different way – it's ambiguous if the action was successful or not.
