### ISSUE TITLE
Doesn't show success messages when removing/creating `ACK/DT` & `Comments`

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#272]
## Describe the bug
No success messages are displayed as the monitoring module does, when creating/removing `ACK`, `DT` and `Comments`.

**Comment by sukhwinder33445** [comment]
There should also be a success/error message for the custom notification.

When notifications are disabled for the host/service:

- The user sends a custom notification but nothing happens. A failed message with reason should appear 
- `OR` `send custom notification` button should be disabled.

**Comment by nilmerg** [comment]
@sukhwinder33445 If forced, a custom notification is sent regardless.

**Comment by nilmerg** [comment]
As discussed: We should show a notification for every successful action. Be it check now, adding a comment or changing the command transport configuration.
