### ISSUE TITLE
Dropdown menu shouldn't be rendered on remove/delete actions

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#273]
## Describe the bug
The `Add to Dashboard` and `Add to Menu` dropdown menus shouldn't be rendered upon `remove/delete` actions.

**Comment by nilmerg** [comment]
Were the comment and downtime detail the only thing you had in mind here? If yes, I'd close here.

**Comment by Yonas-net** [comment]
Yes, I think so, since it doesn't seem to occur anywhere else except in `config/module/icingadb` and everything is done correctly there.
