### ISSUE TITLE
User detail empty values

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#279]
## Describe the bug
Empty values look bad.
 
There should be a `-` for empty values and a `:` after keys.

## Screenshots
Now:

![Screenshot 2021-08-25 at 11 15 43](https://user-images.githubusercontent.com/54990055/130765129-897bdd74-f5b7-4730-ad2b-384c8a1bcf1d.png)

After:
![Screenshot 2021-08-25 at 11 18 08](https://user-images.githubusercontent.com/54990055/130765132-f15b23b0-bf46-4650-bdc5-47930c9ba741.png)

**Comment by nilmerg** [comment]
> and a : after keys.

We have nowhere a colon after keys in such presentations.

**Comment by sukhwinder33445** [comment]
The following issues could also be fixed for better readability:

![Screenshot 2021-08-25 at 16 43 47](https://user-images.githubusercontent.com/54990055/130813735-75a3ac36-9e6b-4cea-988d-3d06054e439b.png)

**Comment by nilmerg** [comment]
Whoof, nice find!
