### ISSUE TITLE
Tactical overview: Down/critical amount overflows if number exceeds 3 digits

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#280]
## Describe the bug
Down/critical amount overflows if number exceeds 3 digits

![Screenshot 2021-08-25 at 11 47 36](https://user-images.githubusercontent.com/54990055/130769458-960b4f46-1d57-4168-b8d7-b97d3dd373c7.png)

## Additional context
Changing the `font-size` from `6em` to `4em` allows 5 digits to be fit in.

![Screenshot 2021-08-25 at 11 57 13](https://user-images.githubusercontent.com/54990055/130770245-d207214d-1477-4524-aa98-e033c95c0b44.png)

**Comment by nilmerg** [comment]
Have you put those in manually? I believe real values are shortened to e.g. `20k` or so :thinking:

**Comment by sukhwinder33445** [comment]
> I believe real values are shortened to e.g. `20k` or so 🤔

Yes, you are right.
I added some more hosts to test this with real values. And used the value of host up for down. The result is this:

![Screenshot 2021-08-25 at 12 29 04](https://user-images.githubusercontent.com/54990055/130775085-cbae85fd-ec0f-4227-a624-70b86f392a00.png)

It shows 3k, but the actual value is 3419, so almost 3.5k. So there are 419 hosts missing here 🤔 . Is the actual value not so important here?

**Comment by sukhwinder33445** [comment]
It helps when we set the precision to `-2` instead of `-3`.

https://github.com/Icinga/icingaweb2/blob/bbd36d5f83a29debbb4a72e79547ee7c4b35dbe0/library/Icinga/Chart/Donut.php#L370-L377

After this change, the `font-size` is still a problem if the number is above `10049`.

![Screenshot 2021-08-25 at 13 40 40](https://user-images.githubusercontent.com/54990055/130784451-ce44ca97-b0b9-4f1b-bfa7-f84e957e3e4a.png)

**Comment by nilmerg** [comment]
I think the purpose of the method you've linked is to only produce integers. Exactly for this reason you're showing, as almost any fraction above 1000 leads to an overflow.

I don't think of this as a real issue. When ever is the critical count really that high? And even if so, I think that the label overflows is the least thing anyone is interested in then. :joy:

The big numbers inside the donuts are only an approximation, they give a quick hint about the scale of the number behind it. Anyone really interested in the real number can see that in the footer below.

**Comment by sukhwinder33445** [comment]
Yes, I see. Thank you for the explanation. I am closing this issue.
