### ISSUE TITLE
Missing `Host/Service` notification `states/types`, `TimePeriods` in user datail

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#281]
## Describe the bug
The `Host/Service` notification filter `states` and `types`, `TimePeriods` etc. are missing in the user details.

**Comment by nilmerg** [comment]
`states` and `types` can easily be shown. `TimePeriods` however are a different beast, as these require a dedicated widget and are therefore a separate enhancement to me.

**Comment by sukhwinder33445** [comment]
> `TimePeriods` however are a different beast

How can i add these? I need a hint please 😄  .

**Comment by nilmerg** [comment]
There is currently no way to add Timeperiods. Hence why I see this as *separate* enhancement.

**Comment by sukhwinder33445** [comment]
Ok, I will create a new issue for this.

**Comment by flourish86** [comment]
Wouldn't it make sense, to put the fields in a new section, e.g. "Notification Settings".

![Screen Shot 2021-09-09 at 16 04 43](https://user-images.githubusercontent.com/6977434/132700917-98fc4dad-853f-491c-85e3-cf6bf528ba96.png)
