### ISSUE TITLE
Dis/enabling Fcmds globally doesn't apply till manual reloading 

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#283]
## Describe the bug
When you disable/enable the Feature Commands globally, it doesn't have any effect until you manually reload the browser/Tab.

**Comment by Yonas-net** [comment]
Besides, when you for example disable `Active Hostchecks` globally, all hosts aren't checked active, however, the `Active Checks` checkbox of each `Host` isn't disabled.

**Comment by nilmerg** [comment]
> however, the Active Checks checkbox of each Host isn't disabled.

This working as intended. The checkboxes in an object's detail resemble its individual configuration state. It's not an indication if an object is *in fact* actively checked.
