### ISSUE TITLE
Host/Service group right column view mode switcher not working correctly

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#284]
## Describe the bug
Host/Service group right column view mode switcher not working correctly. If you change the view mode in the right column, this affects the left column.

## To Reproduce

1. Host Groups.
2. Select a group.
3. Select a host.
4. Select a group in host detail view (right column).
5. Change the view mode of view mode switcher (right column).

![Screenshot 2021-08-25 at 15 20 48](https://user-images.githubusercontent.com/54990055/130800116-18a57380-93e0-418a-b39b-779f79ffab19.png)

**Comment by nilmerg** [comment]
> this affects the left column

The left column is closed, for me. Is that what you mean?

**Comment by sukhwinder33445** [comment]
No. When you change the view mode in the right column for the first time, the view mode for the left column changes (this should not happen). And the right side still remain as it was before.

**Comment by nilmerg** [comment]
Nope. Left column closes and right column (then the only col) updates correctly. The left column shouldn't close of course, but the update is as of now working as intended. See #260 for that.

**Comment by sukhwinder33445** [comment]
@Yonas-net tested this and it works fine on his device. On my device it still doesn't work (maybe it takes too long to load 😆 ).

**Comment by nilmerg** [comment]
This is weird.

* If having a hostgroup detail open on the left **without a `view` parameter**, interacting with a viewmode switcher on the right updates the left column and the right is only updated after its autorefresh
* If having a hostgroup detail open on the left **with a `view` parameter**, doing the same interaction on the right closes the left column and renders the updated right column left

Here's definitely something wrong with what submitting the viewmode switcher will update.

**Comment by Yonas-net** [comment]
That's exactly what I was going to write 😆 . This also applies to `Hosts` => `Host services` 😔 . Without the `view` param everything works as expected.

**Comment by Yonas-net** [comment]
> The left column shouldn't close of course,

I think this is actually intentional, that when `col1` and `col2` do have the exact same url **path**, `col1` is supposed to be shifted. See [here](https://github.com/Icinga/icingaweb2/blob/bbd36d5f83a29debbb4a72e79547ee7c4b35dbe0/public/js/icinga/loader.js#L645-L650).

**Comment by nilmerg** [comment]
> This is weird.

This is fixed it seems with #331.

> I think this is actually intended

It's not. It's a side-effect of an intended effect. The part you've linked is intended to cover the case that a configuration form is on the right and redirects back to list upon successful submit. Then the right column is indeed not required anymore and the "redirect" is loaded into the left column. But here it's not a configuration form. So this is a bug in Icinga Web 2.

**Comment by Yonas-net** [comment]
The view mode switcher is also somehow a configuration form. And the left column closes only when the view mode is submitted, so I am not sure how to distinguish this from the others.
