### ISSUE TITLE
Center load more page separator

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#285]
## Describe the bug
It looks much better when it is centred.

Now:

![Screenshot 2021-08-25 at 17 01 29](https://user-images.githubusercontent.com/54990055/130815739-ee9dc860-9cf8-4501-9668-96dcfb582b42.png)

After:

![Screenshot 2021-08-25 at 17 02 36](https://user-images.githubusercontent.com/54990055/130815732-7ae2e9de-7818-44d4-9d42-61598a554381.png)

Setting the left margin of `.list-item.page-separator a` to `0` instead of `3.5em` can do the job.

**Comment by nilmerg** [comment]
The goal here was to keep the structure of the list. The separator has no visual, hence it doesn't span as far to the left.

@flourish86 Your opinion please.

**Comment by sukhwinder33445** [comment]
Should i center the separator or leave it as it is and close this issue?

**Comment by nilmerg** [comment]
> If you want I can come up with new mockups, where these problems are addressed.

Yes. Please.

**Comment by flourish86** [comment]
I came up with some mockup of a redesign load more interaction.

![Desktop Copy 5](https://user-images.githubusercontent.com/6977434/134934550-929c55b9-ddc0-4133-bb2d-cedbe0349f22.jpg)

Here are the full screen mockups.

### Redesigned Load more button

![Desktop Copy 6](https://user-images.githubusercontent.com/6977434/134934770-d38c709f-68ff-429f-b78b-d6bb48d11dd7.jpg)


### Hovered button design

![Desktop Copy 7](https://user-images.githubusercontent.com/6977434/134935070-e7cf5d67-fc70-4ab3-916d-33b31dab0ff8.jpg)


### List with newly loaded page

![Desktop Copy 8](https://user-images.githubusercontent.com/6977434/134935004-b83a5ad2-aada-4628-a3cf-1f599cc8c052.jpg)
