### ISSUE TITLE
Missing `Escalated` attribute in event details

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#287]
## Describe the bug
Since this attribute is being displayed with the monitoring module, it should probably also be included in the event details of Icinga DB.

**Comment by nilmerg** [comment]
Ping @lippserd

**Comment by julianbrost** [comment]
Well, probably some deprecated leftover from Icinga 1? At least Icinga 2 just always sets it to 0:
https://github.com/Icinga/icinga2/blob/95cdc00ad4e1ab788794322c92c54cd3f5c8c2bf/lib/db_ido/dbevents.cpp#L872

**Comment by nilmerg** [comment]
Then I'd say, *working as intended*.
