### ISSUE TITLE
Notification detail uses improper wording

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#289]
## Describe the bug
This notification received 4 users.

## Expected behavior
4 users received this notification.

## Screenshots
![Screenshot from 2021-08-26 12-18-32](https://user-images.githubusercontent.com/16668527/130946160-48ad3caa-3b7c-4d21-adbc-82c23188573b.png)

**Comment by flourish86** [comment]
I'd rather use:

"The notification was sent to 4 users", since we can't guarantee, if they received it in the end.

Compare the WhatsApp check marks:

![whatsapp-tick-marks-meaning copy](https://user-images.githubusercontent.com/6977434/131310680-851f3c63-30bc-49c8-928c-94acb733e5ac.jpg)
