### ISSUE TITLE
Closing parentheses not inserted at the correct location in the searchbar

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#291]
## Describe the bug
When closing a pair of parentheses, the closing one isn't inserted inside the expression but at the very end.

## To Reproduce

1. Define two expressions
2. Insert at `(` at the very start
3. Add a logical operator after the first expression
4. Add a third expression after the new logical operator
5. Insert a `)` after the third expression

## Expected behavior
The closing parenthese is inserted at the correct location.

**Comment by sukhwinder33445** [comment]
I was not able to reproduce this error as described above. 
There should be three expressions with `(` at the very beginning and `)` at the end, right? Am I doing something wrong?

## Expressions

![Screenshot 2021-09-01 at 17 35 44](https://user-images.githubusercontent.com/54990055/131700936-a17c233b-8b18-4494-a992-168a3fb6e5ed.png)

## After submit

![Screenshot 2021-09-01 at 17 35 56](https://user-images.githubusercontent.com/54990055/131701126-6668d12c-2fd8-4690-9905-289709eb2c41.png)

And this result seems correct to me.

**Comment by nilmerg** [comment]
But after the submit the `)` is re-located, isn't that a sign that before the submit it's placed wrong?

**Comment by sukhwinder33445** [comment]
After submitting, the parentheses are relocated if they were wrong before. I thought that was intentional?

You mean that they should be marked `red` if they are not positioned correctly?

**Comment by nilmerg** [comment]
I mean, that they do is fine. But they shouldn't have to.
