### ISSUE TITLE
The view mode switcher shows less items when switching from the minimum to the common or detailed view.

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#298]
## Describe the bug
The view mode switcher shows fewer items when switching from the minimum to the common or detailed view.
This problem occurs when there is no pagination control but the` Load more` button is present.

## To Reproduce

1. Go to History/Notification (Make sure that the `minimum view` is active in the `view mode switcher`.)
2. Load at least one more page (there should be 2 pages or more).  

> In `minimal mode`, the list is limited to 50 entries by default. The two pages therefore show `2 x 50 = 100 entries`.
> In `common` and `detailed view` mode, the default limit is set to 50. So `100 / 25 = 4 pages` are needed to load all entries that were visible in minimum mode.

3. Switch to `common/detailed view mode`. 
4. There are only `3 pages x 25 = 75 items`.

## Expected behavior

When the view mode is switched, always the same number of entries should be displayed. In this case, 4 pages are needed to list 100 entries.

**Comment by nilmerg** [comment]
I'd say the different behavior is indeed the expected one mentioned here.
