### ISSUE TITLE
Object header still clickable and has subject links in some areas

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#306]
## Describe the bug
When in an object's detail we don't want the header showing a list item to have any links. The host header though in the `Services` tab and possibly also in the history has still such. There may be more detail headers with this problem.

## Expected behavior
Detail headers don't provide clickable list items nor have object links referring to the same objects.

**Comment by sukhwinder33445** [comment]
Should I remove the host name in the list of services on the "Services" tab because they are also superfluous?
If yes, the host name or just the links?

![Screenshot 2021-09-01 at 16 30 10](https://user-images.githubusercontent.com/54990055/131690580-db50317c-94dd-43f5-919c-43b8bffba561.png)

**Comment by nilmerg** [comment]
They are, kind of, but I wouldn't go that far here. This is about the header only.
