### ISSUE TITLE
Ellipsisize downtime list caption

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingadb-web#34]
![Screenshot 2020-03-17 at 16 45 53](https://user-images.githubusercontent.com/6977434/76874092-f091ce00-686e-11ea-8e4b-10d108f49652.png)

**Comment by lippserd** [comment]
Affirmative. Do you take care of a fix?

**Comment by flourish86** [comment]
> Affirmative. Do you take care of a fix?

I'll see what I can do.
