### ISSUE TITLE
Markdown in notes not working

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icingadb-web#35]
icingadb-web: 1.0.0-rc1
Something like this doesnt work:
`<p><strong>Stage:</strong> Development<br /><strong>OS:</strong> RHEL</p>`

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll look into this.

Best regards,
Eric

**Comment by nilmerg** [comment]
Hi,

are you referring to comments by chance? Because I've found several occasions where we forgot to render markdown (e.g. comments, downtimes) but notes are already rendered as markdown.

**Comment by nilmerg** [comment]
> Hi,
> 
> are you referring to comments by chance? Because I've found several occasions where we forgot to render markdown (e.g. comments, downtimes) but notes are already rendered as markdown.

Nevermind. I only looked at the code where they're indeed rendered as markdown but in the UI they're escaped again so that the raw HTML appears.
