### ISSUE TITLE
PHP Redis dependency issues

### ISSUE THREAD

**Issue by petulko8080** [Icinga/icingadb-web#36]
Just make fresh install of icingadb-web and after enabling it and configuring database, clicked on redis config and from this moment my navigational menu is broken, just get error info:
Method Icinga\Web\Navigation\Renderer\RecursiveNavigationRenderer::__toString() must not throw an exception, caught Error: Class 'Redis' not found

**Comment by eifelmicha** [comment]
I had the same issue. Did you install redis php package? in debian it's named php-redis

**Comment by mcktr** [comment]
Hi,

you also must install the Icinga PHP Library from here: https://github.com/Icinga/icingaweb2-module-ipl

Best regards
Michael

**Comment by eifelmicha** [comment]
FYI: I had installed this module when i got the "Class Redis not found" error.

**Comment by petulko8080** [comment]
ipl  module already instaled,
icingadb installed form centos repository, so i have those "redis" packages installed alredy:
hiredis
icinga-redis
icingadb-redis
php-pecl-redis
redis
sclo-php71-php-pecl-redis

tried all (what i can find) php-redis packages one by one or combinations without any luck

**Comment by eifelmicha** [comment]
So can you provide more details on your environment?

**Comment by petulko8080** [comment]
what exactly you need know?
Centos 7.1
icinga2/icingadb installed from repository, vesion 2.8.0-rc1
original php installed from centos repository, v 5.4.16
new php 7 (php 7.1, packages rh-php71 ) from centos-sclo-rh repository
icingadb from icingadb repository, version 1.0.0-rc1
ipl latest, 0.5.0

**Comment by lippserd** [comment]
@petulko8080 `sclo-php71-php-pecl-redis` is the correct PHP Redis package for a RHEL / CentOS 7 environment. Did you restart `php-fpm` after installing this package?

Further, please provide the error from the web server logs or Icinga Web 2 logs.

Anyway, we need a better dependency management in Icinga Web 2. We'll post a link here for reference once we've created an issue.

**Comment by petulko8080** [comment]
ok, so i found a problem : because there was no dependency in installation instructions, i just installed highest php-redis package _sclo-php71-php-pecl-redis5_ , after change this to _sclo-php71-php-pecl-redis_ new web working fine

thank for help

after some testing, still primary use old web ui because of grafana module, but like new one, more clear and fater, will look forward for improvements, especialy for grafana as metioned. But anyway, good work.

**Comment by mwaldmueller** [comment]
sclo-php71-php-pecl-redis package is no longer available in CentOS 7.7, so I opened an issue for icingaweb https://github.com/Icinga/icingaweb2/issues/4128

**Comment by nilmerg** [comment]
We'll upgrade the php version requirement for RHEL / CentOS 7 to v7.3 for Icinga Web 2.8.0.
The testing repository is already updated with this change and provides `icingaweb2-2.8.0-0.rc1.2` for this.
Current upgrading docs can be found [here](https://github.com/Icinga/icingaweb2/blob/3776e8a23384dc3d12082ca782228c91b3c98c25/doc/80-Upgrading.md#upgrading-to-icinga-web-2-28x).
