### ISSUE TITLE
Detail view produces "Uncaught Error: Call to a member function select()" when choosing an item

### ISSUE THREAD

**Issue by eifelmicha** [Icinga/icingadb-web#37]
### Issue and Steps to Reproduce
After installing and configuring IcingaDB in a dockerized Environment, the monitoring module in all levels and IcingaDB at root levels work fine.

However if i chose an e.g. an hostitem in IcingaDB and want to get down to the "detail view" only errors are shown in that tab and it's always:

```
Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php:502
Stack trace:
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php(439): Icinga\Module\Monitoring\Object\MonitoredObject->fetchHostVariables()
#1 /usr/share/icingaweb2/modules/map/library/Map/ProvidedHook/Monitoring/HostActions.php(19): Icinga\Module\Monitoring\Object\MonitoredObject->fetchCustomvars()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/HostActionsHook.php(50): Icinga\Module\Map\ProvidedHook\Monitoring\HostActions->getActionsForHost()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/ObjectActionsHook.php(21): Icinga\Module\Monitoring\Hook\HostActionsHook->getActionsForObject()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(82): Icinga\Module\Monitoring\Hook\ObjectActionsHook->getNavigation()
#5 /usr/share/icingaweb2/modules/icinga
```

Works fine are:
- Root Level
- Health
- everything without drill in / detail view

### Versions
IcingaDB Webmodule: 1.0.0-rc1

### Screenshots
![image](https://user-images.githubusercontent.com/37506516/77222190-5a50f700-6b51-11ea-8bf6-3cbb73355af5.png)
![image](https://user-images.githubusercontent.com/37506516/77222221-908e7680-6b51-11ea-93b4-6856aa8411b9.png)

#### Expected
Detail view like seen on first page

#### Actual
Uncaught Error: Call to a member function select()

### Additional Details
* Installed packages:
OS: Debian Buster in Docker
Icinga2: r2.12.0-rc1-1
icinga-redis: 5.0.7-4
icingadb: 1.0.0~rc1-1
PHP: 7.4.4 (modules: cli \ fpm \ ctype \ intl \ json \ gettext \ readline \ opcache \ mbstring \ xml \ curl \ mysql \ pgsql \ gmp \ yaml )
PHP-Redis: 5.2.0+4.3.0-1+0 (sury)

Did i miss to install something?

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This seems to be an issue in our compatibility layer for hooks for of monitoring module. We'll look into this.

All the best,
Eric
