### ISSUE TITLE
Overdue visualization

### ISSUE THREAD

**Issue by distahl** [Icinga/icingadb-web#39]
Can you please make the overdue visualization an option or at least less foregrounded?

The greyed line with a big, fat red "overdue since ..." is way too much in my opinion. It draws all attention and makes it hard to see the real issues.

Personally I don't care that much if some checks are 5min later then they sould be. It's not great but sometimes you cannot do much about this. E.g. if your server isn't able to handle that much checks simultaniously.

Also please note that passive-check-only hosts are affected even more by this. Because they are always displayed with this greyed red visualization if not getting updates periodically.

**Comment by dmitriy-terzeman** [comment]
I find new Overdue more informative then it was before, it indicates that you have a performance problems with your environment, in cases when check should be scheduled each minute but have been not executed for 10 hours it indicates that your infra have problems.

Maybe it worth to disable Overdue check for passive only Host/Service checks, or for passive checks without interval option

**Comment by distahl** [comment]
But it's not displaying this only if you have an 10h overdue. It also displays this if you only have a 2min overdue.

We are having 16k hosts and 57k services. I don't think I will be able to finetune all the checks to get rid of this overdue thing, which will make it nothing more than annoying :-(

**Comment by nilmerg** [comment]
Hi,

we're already considering a grace period for this indicator. Currently that's the check's latency (time gone between scheduled and executed) plus its execution time multiplied by 2. If checks are regularly executed way later than scheduled this *should* be covered by the latency and if a check runs often into a timeout this should be covered by the execution time. Though I'm not sure how the latency and execution time is actually calculated and updated by Icinga, maybe @N-o-X or @Al2Klimov can provide a hint on this.

**Comment by N-o-X** [comment]
Hi,

execution time and latency are calculated as follows.

Execution time:
```
ExecutionTime = ExecutionEnd - ExecutionStart
```

Latency:
```
Latency = ScheduledEnd - ScheduledStart - ExecutionTime
```

Both values are updated (in Redis) by the Icinga DB feature on any state related change (e.g. check result)

**Comment by nilmerg** [comment]
Is `ScheduledEnd` pre-calculated or the actual time the check finished?

**Comment by N-o-X** [comment]
In most cases `ScheduledEnd` is just the time we got the check result, which is quite a bit misleading in my opinion. @Al2Klimov did I miss something here?

**Comment by Al2Klimov** [comment]
`CheckResult#schedule_end` is pre-calculated, `CheckResult#execution_end` is the actual time the check finished.

**Comment by Al2Klimov** [comment]
Hm, it's actually == `CheckResult#execution_end`, not pre-calculated. But IMAO `CheckResult#execution_end` is still _the_ source for the actual time the check finished.

**Comment by nilmerg** [comment]
@distahl So, I tried to heavily overload my testing environment. This caused the latency for my services to rise up to 30 minutes at times. Though, as overdue marked were just about 4 to 6 services at once (of ~3k). Of course, this are not the same circumstances as in your environment, but it shows me that the grace period is working well on my end. Or at least, I don't have *a ton of services* which are overdue.

At the moment I see no urgent reason to refactor this. Please consider this a wake-up call to re-configure your check-intervals. You may also ask on the [forums](https://community.icinga.com) for more ideas on the matter.

--
If anyone else faces this issue and can't solve it by re-configuration or more resources, please tell us your situation and we may think of a way to enhance how overdue checks are detected. Thanks.

**Comment by lippserd** [comment]
Hi @distahl,

I had a little chat with @nilmerg about this topic and I do think that we need more information about your setup in order to elaborate this further:

- Do you only have checks with 5 minutes for the check interval? If not, please share your check interval distribution.
- How many objects are overdue? And for how long? Do you have an average here?
- Is this a permanent situation? Or does it only happen after reloads or other events?
- Could you share the specs of the machine that is running Icinga? Is only Icinga running on that machine?
- Also, please share the output of [v1/status](https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#status-and-statistics).

For the passive only checks I think it makes sense to align this properly with the freshness checks.

All the best,
Eric

**Comment by distahl** [comment]
Sorry for this very late response. I was occupied by other things in the meantime.

Thanks for the xplanation of the different timer values.

I reduced the the amount of hosts and services on my test environment and now I don't see any overdue messages anymore.

But I think this discussion is going into the wrong direction. Of cause I know, that readjusting the check intervals will lead into less overdue, but this wasn't my question/wish in the first place. I just wanted to know if you can add an option to make the overdue visualization in the overview lists (not details) disappear or less foregrounded. Because sometimes you can't or don't want to fine tune all of your check intervals.

**Comment by nilmerg** [comment]
> I just wanted to know if you can add an option to make the overdue visualization in the overview lists (not details) disappear or less foregrounded.

We may consider changing this if more people are interested in it.
