### ISSUE TITLE
Search bar terms disappear

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#433]
## Describe the bug
Terms in the search bar disappear, reappear after manually refreshing the page.

## To Reproduce
1. `Host detail` -> Select a service from the `Services` section on the Host tab.
2. Service list with search bar terms appears.
3. Click on the name of the host/service to see the detail view in the right container (the service list has now moved to the left container)
4. After a few seconds, the terms in the search bar in the left container disappear.

Note: Appears when auto reload is enabled.

## Expected behavior
The terms in the search bar should not disappear.

**Comment by nilmerg** [comment]
I cannot reproduce this at the moment, can you?

**Comment by sukhwinder33445** [comment]
Tested it again and can't reproduce it on my system either.

Tested on Ravi's system and it is reproducible. and now the active state of the selected item also disappears. 
To reproduce the problem, follow the same steps as above and wait for the auto refresh to trigger. The selected (active) item in the left column is no longer active.
