### ISSUE TITLE
Safari: controls separator line missing

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingadb-web#439]
## Screenshots

![Screenshot 2021-11-10 at 12 36 42](https://user-images.githubusercontent.com/54990055/141106795-49ba25e7-eacc-43ad-9083-74f8253a2b97.png)

![Screenshot 2021-11-10 at 14 27 35](https://user-images.githubusercontent.com/54990055/141122230-78c20126-9612-473a-b301-3556871790b5.png)

**Comment by flourish86** [comment]
At which zoom level are the screenshots made? Looks like a rounding error to me.

Also look at the gap between the active tabs and the controls.

**Comment by sukhwinder33445** [comment]
I cannot reproduce this.

**Comment by sukhwinder33445** [comment]
I cannot reproduce this.

**Comment by sukhwinder33445** [comment]
I cannot reproduce this.
