### ISSUE TITLE
Now bubble overlaps scheduled start bubble of flexible downtimes

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#44]
![Bildschirmfoto von 2020-04-01 14-28-29](https://user-images.githubusercontent.com/16668527/78137249-45b01100-7425-11ea-9023-4ac7e884bbff.png) ![Bildschirmfoto von 2020-04-01 15-20-43](https://user-images.githubusercontent.com/16668527/78141882-6a5bb700-742c-11ea-836d-f71373c4aa1d.png)

**Comment by flourish86** [comment]
I see the problem and this was also regarded when initially implemented.

The "Now" bubble is the smallest and so the most likely one to be overlapped completely, so it was put into the foreground. If this other bubbles are overlapped, they can be put in foreground by hovering on them.

I agree, that this is far from ideal, but I suspect there won't be a fix without using Javascript, which we usually try to avoid.

**Comment by nilmerg** [comment]
LOL. I didn't knew that hovering shows the underlying bubble! Yes, not perfect, but acceptable if JS should be avoided. (provided that this workaround is known)
