### ISSUE TITLE
Host icons for Icinga Web internal icons not showing

### ISSUE THREAD

**Issue by ecm75** [Icinga/icingadb-web#456]
## Describe the bug
Icingaweb internal icons not showing for hosts (eg print) external images work fine (eg. tux.png).

## To Reproduce

1. Configure a Icingaweb2 internal image as hostimage. (eg. print)

2. Show the host in std. host view:
![grafik](https://user-images.githubusercontent.com/24545783/141761610-ed1fbb00-c803-4070-8343-32fd5464a973.png)

3. Show the host in Icinga DB view:
![grafik](https://user-images.githubusercontent.com/24545783/141761834-7dec333f-2db1-4488-9c01-5e467f89ad68.png)

## Expected behavior
The internal icon should be visible in both cases.

## Screenshots
see above

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc2 (f402e1e5dc4ffde136ab0fed109925f2a754ca86)
* Icinga Web 2 version (System - About): 2.9.4 (d208d1ccfef86606984739e6357138c459146134)
* Web browser: Google Chrome 95.0.4638.69 / Firefox 78.15.0esr
* Icinga 2 version (`icinga2 --version`): r2.13.2-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc2-dev
* PHP version used (`php --version`): 7.3.31-2
* Server operating system and version: Debian 10 / Kernel 4.19.0-17-amd64

**Comment by lippserd** [comment]
Hi @ecm75,

Thanks for the report. Bug confirmed.

All the best,
Eric
