### ISSUE TITLE
Command transport passwordfield always show the password (aka is not a password field)

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingadb-web#459]
## Describe the bug
Command transport passwordfield always show the password

## To Reproduce
Configure a command transport, the api password is always shown. Other password fields hide the password

## Expected behavior
The password should be also hidden like all other password fields in icingaweb2

## Screenshots
![grafik](https://user-images.githubusercontent.com/6574967/142383509-4bf7ec31-b219-46d3-ae9f-f9ce6722af06.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc2
* Icinga Web 2 version (System - About): 2.9.4
* Web browser: FireFox, Chrome, whatever
* Icinga 2 version (`icinga2 --version`): 2.13.2-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc2-dev
* PHP version used (`php --version`): 8.0.12
* Server operating system and version: CentOS Linux 8

**Comment by lippserd** [comment]
Hi @Mikesch-mp,

Thanks for the report. Bug confirmed!

All the best,
Eric
