### ISSUE TITLE
Host Details broken - Integrity constraint violation: 1052 Column 'host_id' in where clause is ambiguous

### ISSUE THREAD

**Issue by Clasko** [Icinga/icingadb-web#464]
## Describe the bug
Host Detail Page is completly broken:

```
#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(401): PDO->prepare(String)
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec(String, Array)
#2 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(709): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#3 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(127): ipl\Orm\Query->yieldResults()
#4 [internal function]: ipl\Orm\ResultSet->yieldTraversable(Object(Generator))
#5 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(107): Generator->valid()
#6 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(56): ipl\Orm\ResultSet->advance()
#7 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(681): ipl\Orm\ResultSet->current()
#8 /usr/share/icingaweb2/modules/icingadb/application/controllers/HostController.php(80): ipl\Orm\Query->first()
#9 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(728): Icinga\Module\Icingadb\Controllers\HostController->indexAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

## To Reproduce
Just a fresh installation of IcingaDB RC2

## Expected behavior
A working Host Details page.

## Screenshots
![grafik](https://user-images.githubusercontent.com/510177/143444180-216265a6-f73e-4d26-aa4b-102b77c48df7.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc2-dev
* Icinga Web 2 version (System - About): 2.9.5
* Web browser: Firefox 89.0.2
* Icinga 2 version (`icinga2 --version`): 2.13.2-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc2-dev
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: CentOS Linux release 7.9.2009 (Core)

**Comment by nilmerg** [comment]
> /usr/share/icingaweb2/modules/icingadb/application/controllers/HostController.php(80): ipl\Orm\Query->first()

On that line [is nothing](https://github.com/Icinga/icingadb-web/blob/v1.0.0-rc2/application/controllers/HostController.php#L80) when on 1.0.0-rc2.

Please make sure your installation is really 1.0.0-rc2.

**Comment by Clasko** [comment]
You're right. Versionstring in Icinga Web 2 said rc2-dev, rpm Package was rc1.

```
# rpm -qi icingadb-web
Name        : icingadb-web
Version     : 1.0.0.rc1.664.gaefd0e1
```
All good now. Thanks for the quick response.
