### ISSUE TITLE
Add support for redis password

### ISSUE THREAD

**Issue by flybyray** [Icinga/icingadb-web#472]
Currently it is not possible to use redis password.

Some other icinga components would support that: https://github.com/Icinga/docker-icingadb/blame/master/README.md#L30

https://github.com/Icinga/icingadb-web/blob/2ffd820a74cbd70b5e385db369174647eafc2f00/library/Icingadb/Common/IcingaRedis.php#L156

**Comment by nilmerg** [comment]
[Icinga DB](https://github.com/Icinga/icingadb/blob/master/doc/03-Configuration.md) itself doesn't document this. Redis v6 though, which is required anyway, supports passwords in [protected mode](https://redis.io/topics/security). @Al2Klimov Can I safely assume it is *safe* to implement support for that?

**Comment by Al2Klimov** [comment]
Why.. not?

**Comment by lippserd** [comment]
> Why.. not?

Yes it is safe. The only thing missing is the documentation.
