### ISSUE TITLE
Things disappear when disabling monitoring module

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#50]
If I disable the "monitoring"-module the following things disappear:

-  Dashlets in Dashboard

- Search field

- Problems

- Monitoring-Status

**Comment by nilmerg** [comment]
Hi,

we forgot to provide default dashboards and the search provider :facepalm: , thanks for pointing this out!

Though, the host and service problems are now the badges (These are now clickable like any other badge) in the respective menu section. The monitoring status as well, that's what can be found under the `Health` section.
