### ISSUE TITLE
Tactical Overview

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#51]
I miss a few things in "Tactical Overview":

- should be on top of the menu

- looks different than from the monitoring-module (frames, right-aligned and additional description, e.g. "Ok")

- a summary would be nice ;-) (also not in monitoring-module)

monitoring module:
![tactical-overview1](https://user-images.githubusercontent.com/3973350/79235085-6fc4f280-7e6b-11ea-8832-5e00da3415ff.png)

icingadb-web module:
![tactical-overview2](https://user-images.githubusercontent.com/3973350/79235197-971bbf80-7e6b-11ea-83d6-3de9b9ad1630.png)

**Comment by nilmerg** [comment]
Hi,

> should be on top of the menu
The menu will be re-structured prior the final release.

> looks different than from the monitoring-module
Works as intended. If you don't like this, tell this @flourish86 and @lippserd :sweat_smile: 

> a summary would be nice ;-) 
What exactly should this summary include?

**Comment by mwaldmueller** [comment]
> Hi,
> 
> > should be on top of the menu
> 
> The menu will be re-structured prior the final release.
Okay, good to know.
> 
> > looks different than from the monitoring-module
> 
> Works as intended. If you don't like this, tell this @flourish86 and @lippserd 😅
Thanks, I will discuss it with them.
> 
> > a summary would be nice ;-)
> 
> What exactly should this summary include?
Total summaries of all Hosts and Services (like in the Host- or Service-submenus).

**Comment by nilmerg** [comment]
> > > a summary would be nice ;-)
>>
> > What exactly should this summary include?
>
> Total summaries of all Hosts and Services (like in the Host- or Service-submenus).

That's what you get in the monitoring's `Monitoring-Status` -> `Statistics` and Icinga DB Web's `Health`.

**Comment by mwaldmueller** [comment]
> > > > a summary would be nice ;-)
> > > 
> > > 
> > > What exactly should this summary include?
> > 
> > 
> > Total summaries of all Hosts and Services (like in the Host- or Service-submenus).
> 
> That's what you get in the monitoring's `Monitoring-Status` -> `Statistics` and Icinga DB Web's `Health`.

Yes, now with icingadb-web module. But in my opinion it should also be visible in "Overview".

**Comment by flourish86** [comment]
> looks different than from the monitoring-module (frames, right-aligned and additional description, e.g. "Ok")

It's the way it is, there's no functional shortcomings, but looks less randomly distributed.
 
> a summary would be nice ;-) (also not in monitoring-module)

We could just add the bottom Status Bar element, that's also apparent in lists, with combined hosts and services data. This would make sense to me and not do any harm.

See
![Artboard](https://user-images.githubusercontent.com/6977434/79328353-2ed5e800-7f16-11ea-8c58-cd82eed2ba0e.jpg)

**Comment by nilmerg** [comment]
> We could just add the bottom Status Bar element

You're kidding? That's just the same information only presented differently. The only detail he's missing is the total count of hosts/services. No need to repeat any information.

**Comment by flourish86** [comment]
> > We could just add the bottom Status Bar element
> 
> You're kidding? That's just the same information only presented differently. The only detail he's missing is the total count of hosts/services. No need to repeat any information.

Haha, you're right.
Then we could just add the total count in the title, can't we?

**Comment by nilmerg** [comment]
Yes, we can!

**Comment by flourish86** [comment]
Here are Mockup of it, containing additional changes:

### General
* Reduce redundant text for additional clarity
** Box Header Titles: "Services Summary" -> "Services", "Hosts Summary" -> "Hosts"
** Critical Count subtitles: "Services Critical" -> "Critical", "Hosts Down" -> "Down"

### Version 1
#### Total in Donut

![Total in Donut](https://user-images.githubusercontent.com/6977434/79345951-107de580-7f32-11ea-8124-fbc7181cabf9.jpg)

### Version 2
#### Total in Box Title

![Total in Header](https://user-images.githubusercontent.com/6977434/79345954-11167c00-7f32-11ea-8574-510e546d20a5.jpg)

**Comment by lippserd** [comment]
Total in the title looks good.
