### ISSUE TITLE
Icingaweb 2.10.0 not loading PHP after enabling IcingaDB web module

### ISSUE THREAD

**Issue by Ramshield** [Icinga/icingadb-web#512]
## Describe the bug
The PHP stuff doesn't load. 

![image](https://user-images.githubusercontent.com/3533440/159988963-42ddea8e-21c9-4c66-a5e1-c7fa8b9d6628.png)

## To Reproduce
Upgrade to >=2.10.0 and enable icingadb web module.

## Screenshots
See above 

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc2
* Icinga Web 2 version (System - About):  2.10.0 (Applies to 2.10.0-1.buster, 2.10.0-2.buster and 2.10.0.20220323.1408+buster-0)
* Web browser: Google Chrome
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.2-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 5.13.19-6-pve
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```
* Icinga DB version (`icingadb --version`): Icinga DB version: v1.0.0-rc2-dev
* PHP version used (`php --version`):
```
PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.31, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.31-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```
* Server operating system and version:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
```

**Comment by Ramshield** [comment]
> check out latest master, that worked for me :)

Yeah that worked, but what a mess to get there.
I had to manually git clone icinga-php-library and icinga-php-thirdparty library for that, checkout the snapshot/nightly branch and then edit the VERSION to remove `-dev` version. 
This is because icingadb-web master only works with some versions that are not in the repositories (???).

**Comment by lippserd** [comment]
> Yeah that worked, but what a mess to get there.

That is true and sorry about that. We're close to final release, so we haven't created a new version in the meantime.
