### ISSUE TITLE
Servicegroups appear empty with service restrictions, even if not

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#514]
## Describe the bug
A servicegroup is empty in the overview list. Clicking on it lists some of its services though.

## To Reproduce
![Screenshot from 2022-03-30 09-00-12](https://user-images.githubusercontent.com/16668527/160771083-2df03768-3409-4bd0-8d6c-f470ba49e1d1.png)

## Screenshots
![Screenshot from 2022-03-30 08-58-26](https://user-images.githubusercontent.com/16668527/160771118-ea4ee4b6-8d60-4497-8d49-09acb2236b36.png)

**Comment by yhabteab** [comment]
In your case, the chosen service group and the service group name specified in the service restrictions differ? Is this intentional? Because I cannot reproduce this error!

**Comment by nilmerg** [comment]
Yes, the shown group includes **all** services in the *dev-docker* environment. The restriction restricts the user to only a subset of these services, the *web* services.

**Comment by nilmerg** [comment]
Umm, not really. For such cases `$forceOptimization` has been introduced. This may be an option, which needs to be used by the UnionQuery, but since this is [bypassed](https://github.com/Icinga/ipl-orm/blob/master/src/Compat/FilterProcessor.php#L36) anyway there is no clear way to solve this right now. Please talk to @lippserd, who's currently working on changing the union implementation.
