### ISSUE TITLE
Permission settings

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#52]
The permission settings for roles should have at least the same options than the monitoring module.

![permissions](https://user-images.githubusercontent.com/3973350/79238025-27a7cf00-7e6f-11ea-9894-774aec1d598c.png)

**Comment by nilmerg** [comment]
Hi,

Icinga DB Web currently has no permissions. It's using the monitoring module's permissions as described in the [configuration chapter](https://github.com/Icinga/icingadb-web/blob/master/doc/03-Configuration.md#configuration).

This of course will change, but we didn't decide if we want to implement the permissions 1:1 or not. This will then be tackled in a different issue. Closing this for now.
