### ISSUE TITLE
Services not listed in servicegroup detail if restrictions are active

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#521]
## Describe the bug
This happens when clicking on the servicegroup. The normal service listing is not affected. Must have something to do with the detail filter.

![Screenshot from 2022-04-07 17-02-05](https://user-images.githubusercontent.com/16668527/162230453-dff78c2c-f02a-4d7c-8950-ae13aabbd578.png)

## To Reproduce
`icingadb/filter/hosts`: `host.vars.env=dev-docker`
`icingadb/filter/services`: `servicegroup.name=web-services-dev-docker|servicegroup.name=db-services-dev-docker&servicegroup.name=all-services-dev-docker`

## Expected behavior
Services are listed.

## Your Environment

* Icinga DB Web version (System - About): master
* Icinga Web 2 version (System - About): master

## Additional context
Not related to or caused by #518.

**Comment by yhabteab** [comment]
> Not related to or caused by #518.

Has absolutely nothing to do with it. Because this fix only affects union queries and moreover I couldn't reproduce this issue until I pulled [this fix](https://github.com/Icinga/icingadb-web/pull/520). So I think it's more related to #520 somehow.

**Comment by yhabteab** [comment]
<img width="1267" alt="Bildschirmfoto 2022-04-08 um 11 18 18" src="https://user-images.githubusercontent.com/57616252/162405915-a2aa93cb-6a80-4109-b8fd-c750126e9146.png">

**Comment by yhabteab** [comment]
Sorry! It is rather [this](https://github.com/Icinga/ipl-orm/pull/44) which causes it!

**Comment by nilmerg** [comment]
> Has absolutely nothing to do with it

That's why I've added the **Not** in front of it..

**Comment by nilmerg** [comment]
> Sorry! It is rather [this](https://github.com/Icinga/ipl-orm/pull/44) which causes it!

Nope, doesn't work even without this change.

**Comment by yhabteab** [comment]
```php
$optimizeChild !== null && $optimizeChild
 || (
          $optimizeChild === null
          && //! (
                       // Not a selected join
                        //isset($this->baseJoins[$relationPath])
                        ! isset($query->getWith()[$relationPath])
                  //)
            && ! $query->getResolver()->isDistinctRelation($relationPath) // Not a to-one relation
)
```

<img width="1267" alt="Bildschirmfoto 2022-04-08 um 11 48 18" src="https://user-images.githubusercontent.com/57616252/162411357-8a090c2f-2383-4048-8df9-1cb01fec8076.png">

**Comment by nilmerg** [comment]
:man_shrugging: 
![Screenshot from 2022-04-08 11-51-11](https://user-images.githubusercontent.com/16668527/162412019-2dc5ab9c-3b7b-43e4-b17e-76fbfa9cf20f.png)
![Screenshot from 2022-04-08 11-51-00](https://user-images.githubusercontent.com/16668527/162412024-7d710799-c7c0-4c41-8fb3-9910240ac789.png)

**Comment by nilmerg** [comment]
Ah wait, nevermind, it's the cause, you're right. I was on the postgres backend, where without this change nothing is shown because the change is gone... @lippserd Please investigate.
