### ISSUE TITLE
User/-group header baseline incorrect

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#531]
## Describe the bug
![Screenshot from 2022-05-06 11-16-21](https://user-images.githubusercontent.com/16668527/167103775-fa7bf2a3-9443-4d76-b20a-9a08e9f08c24.png)

## Expected behavior
The A is on the same baseline as the title.

## Additional context
This used to look fine. Without looking the cause up, this can't be worked on.

**Comment by sukhwinder33445** [comment]
Rc2 release commit has the same bug. We just did not notice it before.
