### ISSUE TITLE
Menu icons

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#59]
Just a visual thing but I miss nice menu icons like e.g. from monitoring module. And in my opinion "Icinga Db" should be "Icinga DB".

icingadb:
![icingadb](https://user-images.githubusercontent.com/3973350/79542810-931ab800-808c-11ea-9df7-9dea22642e2e.png)

monitoring:
![monitoring](https://user-images.githubusercontent.com/3973350/79542821-98780280-808c-11ea-96ea-a3450a7a7b1d.png)

**Versions:**
icinga2: v2.12.0-rc1
icingadb: v1.0.0-rc1
icingaweb2: v2.8.0-rc1
icingadb-web: v1.0.0-rc1

**Comment by friesoft** [comment]
Maybe go one step further and provide a nice overview page like icinga director? :) Then it would be actually useful instead of just mirroring the same links from the sidebar
