### ISSUE TITLE
Incomplete searchresults when using icingadb module only

### ISSUE THREAD

**Issue by Meister1900** [Icinga/icingadb-web#595]
## Describe the bug

When using the icingadb module instead of the monitoring module the searchresults seem to be incomplete.
For example if I search for "msx1pre" the host is diplayed but no services and no Tactical Overview.
But the host has services and I can find them under overview - services.

I think the problem is that the dashlet filter for the services is using:
service.name_ci=\*MSX1PRE\*
And it should be (used to be in the monitoring module):
service.name_ci=\*msx1pre\*|host.name_ci=\*msx1pre\*

This filter logic definitely makes no sense for the Tactical Overview (filters only for "Service Name" although it includes Hosts diagram)

## Expected behavior
All services should be diplayed for the hosts matching the search term.

## Screenshots
![search1](https://user-images.githubusercontent.com/13082032/178732046-f889f914-9504-4a1b-994d-ea24e866511b.PNG)
![services](https://user-images.githubusercontent.com/13082032/178729995-f87f57ed-b381-4e3a-a770-db7fd8e1edf4.PNG)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.11.1

Loaded Libraries:
icinga/icinga-php-thirdparty 	0.11.0
icinga/icinga-php-library 	0.9.1

Loaded Modules:
director 		1.9.1 	
doc 			2.11.1 	
graphite 		1.2.1 	
icingaclassictheme 		0.5.1
icingadb 		1.0.0 	
incubator 		0.17.0 	
migrate 		2.11.1 	
pdfexport 		0.10.2 	
reactbundle 	0.9.0 	
vspheredb 		1.4.0 	
* Web browser used: Firefox 101.0.1
* Icinga 2 version used (`icinga2 --version`):  r2.13.4-1
* PHP version used (`php --version`): 8.1.8
* Server operating system and version: CentOS Stream release 8

**Comment by nilmerg** [comment]
Hi,

you're absolutely correct. The filter conditions are not broad enough.

Thanks for reporting!
