### ISSUE TITLE
Timestamp of last check result is hard to find

### ISSUE THREAD

**Issue by dwt** [Icinga/icingadb-web#600]
## Is your feature request related to a problem? Please describe.
When looking at a check result and it's output, it's hard to determine when that output is from. That means, when I manually request a re-check, it's very hard to see when the results of that check have actually arrived.

## Describe the solution you'd like
I would like to a) have a timestamp near the output view, so I can be sure I see some information that updates / changes every time a new result arrives. I would also b) like to have an entry into the Check statistics that indicates when the check actually finished / provided output.

## Describe alternatives you've considered
Looking into the Source tap, which provides this information. I discarded this, because it's a really awkward workflow to switch over to that tab to look this up, as it looses all the context that is available on the Service tab.

## Additional context
<img width="529" alt="image" src="https://user-images.githubusercontent.com/57199/179675248-7f87a6df-992f-458e-a9d0-75a5ab34bef8.png">

**Comment by nilmerg** [comment]
Hi,

it is already visible in the check statistics (1m 22s ago) or am I misunderstanding something?

**Comment by dwt** [comment]
@nilmerg To my understanding that only specifies that the check has started, not when it finished? 

I am always confused when and wether the check result has arrived. This may be compounded because I have some checks that have longer timeouts than the default 10 seconds.

**Comment by nilmerg** [comment]
>  that only specifies that the check has started, not when it finished?

I don't know exactly, but it seems so. Though, isn't this then the same as you asked for in #493?

**Comment by dwt** [comment]
Oh indeed! I completely forgot about that request. Yes this is almost a duplicate of #493. I'll add a comment there to consider adding a timestamp to the output.
