### ISSUE TITLE
icingadb-web apt package should depend on icingaweb2-module-monitoring

### ISSUE THREAD

**Issue by timonegk** [Icinga/icingadb-web#607]
The code in this repository depends on code in the monitoring module, e.g. https://github.com/Icinga/icingadb-web/blob/master/library/Icingadb/Compat/CompatHost.php#L7
The dependency is not included in the apt package, resulting in stack traces for missing classes when it is not installed with icingadb-web.

## Environment

* Icinga DB Web version (System - About): 1.0.0
* Icinga Web 2 version (System - About): 2.11.1
* Icinga 2 version (`icinga2 --version`): r2.13.4-1
* Icinga DB version (`icingadb --version`): v1.0.0
* PHP version used (`php --version`): 7.4.30
* Server operating system and version: Debian 11, all icinga packages installed from packages.icinga.com

**Comment by nilmerg** [comment]
No. The classes you're talking of are part of an *optional* integration. It should just work if the monitoring module isn't available. If it does not, it's a bug.

You should show the stack trace(s) instead.

**Comment by timonegk** [comment]
When the module is not available, I get the following stack trace when I click on any service in icinga web:
```
Uncaught Error: Class 'Icinga\Module\Monitoring\Object\Host' not found in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Compat/CompatHost.php:9
Stack trace:
#0 /usr/share/php/Icinga/Application/ClassLoader.php(303): require()
#1 [internal function]: Icinga\Application\ClassLoader->loadClass()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(77): spl_autoload_call()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ServiceDetail.php(14): Icinga\Module\Icingadb\Widget\Detail\ObjectDetail->__construct()
#4 /usr/share/icingaweb2/modules/icingadb/application/controllers/ServiceController.php(85): Icinga\Module\Icingadb\Widget\Detail\ServiceDetail->__construct()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(475): Icinga\Module\Icingadb\Controllers\ServiceController->indexAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#7 /usr/share/icingaweb

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```
I get the following very similar stack trace when I click on any host
```
Uncaught Error: Class 'Icinga\Module\Monitoring\Object\Host' not found in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Compat/CompatHost.php:9
Stack trace:
#0 /usr/share/php/Icinga/Application/ClassLoader.php(303): require()
#1 [internal function]: Icinga\Application\ClassLoader->loadClass()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(77): spl_autoload_call()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/HostDetail.php(20): Icinga\Module\Icingadb\Widget\Detail\ObjectDetail->__construct()
#4 /usr/share/icingaweb2/modules/icingadb/application/controllers/HostController.php(81): Icinga\Module\Icingadb\Widget\Detail\HostDetail->__construct()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(475): Icinga\Module\Icingadb\Controllers\HostController->indexAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#7 /usr/share/icingaweb2/library/ve

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

With the module installed, the normal service / host details page is shown instead of the stacktrace, containing PluginOutput, Comments, Downtime, etc.
Maybe this is just a misconfiguration on my part, but in that case, at least the error message could be improved.

**Comment by nilmerg** [comment]
Yeah, well no, it's clearly not intended and caused by Icinga DB Web alone. We'll change this so that it works even if the monitoring module isn't installed.
