### ISSUE TITLE
History tab of some acknowledged hosts throw exception

### ISSUE THREAD

**Issue by krappi01** [Icinga/icingadb-web#610]
When clicking on the History tab of some acknowledged hosts we get the following exception:

> Uncaught TypeError: Icinga\Module\Icingadb\Widget\MarkdownLine::__construct(): Argument #1 ($line) must be of type string, null given, called in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/BaseHistoryListItem.php on line 103 and defined in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/MarkdownLine.php:22
Stack trace:
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/BaseHistoryListItem.php(103): Icinga\Module\Icingadb\Widget\MarkdownLine->__construct()
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/BaseListItem.php(73): Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem->assembleCaption()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/ListItemCommonLayout.php(23): Icinga\Module\Icingadb\Common\BaseListItem->createCaption()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/BaseListItem.php(91): Icinga\Module\Icingadb\Widget\ItemList\HistoryListItem->assembleMain()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/BaseListItem.php(162): Icinga\Module\Icingadb\Common\BaseListItem->createMain()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Common\BaseListItem->assemble()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#17 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#20 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(491): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#21 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#23 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#24 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#25 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#26 {main}

It seems that it only happens for hosts that were already acknowledged in the old (now disabled) monitoring module.
I cant reproduce it when I ack an host in icingaDB-Web directly.

We are using Icinga Web 2.11.1 with icingaDB-Web 1.0.0

As a workaround, I used PHPs null coalescing operator:
`$markdownLine = new MarkdownLine($this->item->acknowledgement->comment ?? '');`

Maybe the issue is related with #609 as we are facing the same problem.

**Comment by nilmerg** [comment]
I doubt it's the same problem. The [icingadb schema](https://github.com/Icinga/icingadb/blob/0061888c404f87158d449d9b3ced82fca269a13b/schema/mysql/schema.sql) even has a comment explaining your exact observation. This hint is on other columns as well, so this may not only affect the comment data.

Thanks for reporting!
