### ISSUE TITLE
Incorrect results for host/servicegroup details

### ISSUE THREAD

**Issue by BorisTrnka** [Icinga/icingadb-web#620]
## Describe the bug
When selecting certain hostgroup's or servicegroup's details we get incorrect result.
According to our testing, improper data fields are used for the filters - "Host Display Name" instead of "Hostgroup Display Name".

## To reproduce
Starting with : `../icingadb/hostgroups?display_name=*linux*`
Continue to one of the numbers, we get this new URL: `.../icingadb/hosts?host.state.soft_state=0&(hostgroup.name=502777.linux&display_name=*linux*)` which provides incorrect result, improper list of hosts (or empty one).
![image](https://user-images.githubusercontent.com/80466164/185412469-05591d48-fc6a-4fd4-a5a5-fd23bd79236c.png)

Comparing with "Monitoring" module URL: `.../monitoring/list/hosts?host_state=0&hostgroup_name=502777.linux&sort=host_severity&(hostgroup=*linux*|hostgroup_alias=*linux*)` - it uses "hostgroup_alias"

See the "display_name" (which seems to refer to **host** display name) vs. "hostgroup_alias" vs. "hostgroup.display_name".
Correcting to `../icingadb/hosts?host.state.soft_state=0&(hostgroup.name=502777.linux&hostgroup.display_name=*linux*)` we get correct list of hosts.
![image](https://user-images.githubusercontent.com/80466164/185412366-e6f62acb-bc40-4ca0-8835-38f78da485f8.png)

Same for services:
Incorrect: `..&(hostgroup.name=502777.linux&display_name=*linux*)`
![image](https://user-images.githubusercontent.com/80466164/185412017-47e80b2a-80a6-4318-8b7f-9b17bc92ace9.png)

Correct: `..&(hostgroup.name=502777.linux&hostgroup.display_name=*linux*)`
![image](https://user-images.githubusercontent.com/80466164/185411872-cbb59240-e9f9-4f9c-8c3d-276d386722ed.png)

For servicegroups:
![image](https://user-images.githubusercontent.com/80466164/185413244-5c9dea7c-caf6-44eb-bcb6-7b4248d5fa6d.png)

![image](https://user-images.githubusercontent.com/80466164/185413396-773c6aeb-f26e-4b27-a17c-bec53db97324.png)

**Comment by nilmerg** [comment]
> Starting with : ../icingadb/hostgroups?display_name=*linux*

You should go with `hostgroup.display_name=*linux*`. That's also what the search bar uses if you accept its suggestions.

The thing with just `display_name` is that it's not specific enough. Clicking on the numbers will use the same filter again but then it's the host display name. If you start with `hostgroup.display_name` this *misinterpretation* doesn't happen.

Though, yeah, we should be able to normalize `display_name` to `hostgroup.display_name` internally, so that clicking on the numbers automatically uses the correct filter.

**Comment by BorisTrnka** [comment]
Hi, thanks for response, but this is how I get there:
![image](https://user-images.githubusercontent.com/80466164/185420923-387493e9-c2b0-4d43-8efe-078533c3eb71.png)

![image](https://user-images.githubusercontent.com/80466164/185422646-ddddbc1c-5250-48d5-97dc-5ee0eccfd9bc.png)

**Comment by nilmerg** [comment]
Ah, I see! Thanks for clearing this up!
