### ISSUE TITLE
Scrollbars when icons are 32x32

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icingadb-web#633]
## Describe the bug
A scrollbar appears even when there are only two items.

## To Reproduce
Add `icon_image = "img/favicon.png"` to the `generic-service` template.

## Expected behavior
There should be no scrollbar.

## Screenshots
![image](https://user-images.githubusercontent.com/8797510/143319694-6562d346-6516-4729-a508-3738fff8f9b4.png)

## Your Environment
* Icinga DB Web version (System - About): 1.0.0
* Icinga Web 2 version (System - About): 2.11.1
* Web browser: Firefox 103.0b8
AND Chromium 105.0.5162.0
AND Edge 103.0.1264.62
* Icinga 2 version (`icinga2 --version`): 2.13.4-1
* Icinga DB version (`icingadb --version`): v1.0.0
* PHP version used (`php --version`): 8.1.2
* Server operating system and version: Ubuntu 22.04

Since the issue, where I mentioned this, was closed I create this separate issue now.
_Originally posted by @Virsacer in https://github.com/Icinga/icingadb-web/issues/463#issuecomment-1193097938_

**Comment by nilmerg** [comment]
Weird. If I try this now I can reproduce it. Thanks for bringing this up again! :+1:
