### ISSUE TITLE
Set `PDO::MYSQL_ATTR_INIT_COMMAND` only for mysql driver

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingadb-web#647]
## Describe the bug

We currently set this option for both drivers (mysql, pgsql), but as we/users have experienced with this option and using only pgsql problems https://github.com/Icinga/icingaweb2-module-reporting/issues/76, this will also fail sooner or later. So, we can fix this now before the users come to this problem.

**Comment by ledvinap** [comment]
This is fixed by https://github.com/Icinga/icingaweb2/pull/4467 in https://github.com/Icinga/icingaweb2
