### ISSUE TITLE
Password of 2nd Redis is not stored correctly

### ISSUE THREAD

**Issue by lbetz** [Icinga/icingadb-web#670]
## Describe the bug
If you configure two redis connections, for the second the parameter host goes to redis.ini, but the password to config.ini!?

```
# cat /etc/icingaweb2/modules/icingadb/redis.ini 
[redis1]
host = "localhost"
password = "supersecret"

[redis2]
host = "localhost"

# cat /etc/icingaweb2/modules/icingadb/config.ini 
[icingadb]
resource = "mysql-icingadb"

[redis]
tls = "0"

[redis1]

[redis2]
password = "supersecret"
```

## To Reproduce
Configure to redis connections.

## Expected behavior
Store all info in one file. 

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.1
* Icinga Web 2 version (System - About): 2.11.1
* Web browser: Firefox
* Icinga 2 version (`icinga2 --version`): 2.13.5
* Icinga DB version (`icingadb --version`): 1.0.0
* PHP version used (`php --version`): 7.4

**Comment by nilmerg** [comment]
This works as designed. What's the issue you have with this?

**Comment by lbetz** [comment]
If you call the mask again, the field Password (Redis2) is empty. It obviously also reads only from redis.ini. Strange design.
