### ISSUE TITLE
"Copy to Clipboard" button for the executed command field in check source

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icingadb-web#677]
Current one has to select and copy the executed command from the source tab of a host or service by hand to execute the command for debugging etc.

While this is not a problem at all, I think, this is slightly unnecessary.

## Describe the solution you'd like
A "Copy to clipboard" button, would be nice.

**Comment by nilmerg** [comment]
Good idea!

**Comment by RincewindsHat** [comment]
sweet!
