### ISSUE TITLE
Hard state changes when it should not

### ISSUE THREAD

**Issue by gjongenelen** [Icinga/icingadb-web#68]
Hi, I've been testing icingadb for a while now, and it works great. But I have one concern:

Why is icingadb reporting a hard-state change when only the soft-state changed once (1/3)? 
<img width="498" alt="Screenshot 2020-04-03 at 22 18 54" src="https://user-images.githubusercontent.com/5789343/78401651-83659300-75f9-11ea-8b7d-77fe685a42cf.png">

In my opinion this should be a soft-state change twice.

Version: rc1

**Comment by lippserd** [comment]
> Although _Recovered_ should suffice.

Yes, absolutely.
