### ISSUE TITLE
find nothing of hosts when do global searching based on display name or address

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#690]
## Describe the bug
Hello,

when doing a global search it will search in the old monitoring in the object, address and display_name for me.
In icingadb it will only search in the object name I think.

## To Reproduce
Disable the old monitoring that you only work in icingadb mode.
Search for something that is in the display_name or address , but is not in the object name (name or name_ci)

## Expected behavior
Find the horsts that find the text in the display name or address.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 2.11.2
* Icinga Web 2 version (System - About): 1.0.2
* Web browser: chrome
* Icinga 2 version (`icinga2 --version`): r2.13.6-1
* Icinga DB version (`icingadb --version`): v1.1.0
* PHP version used (`php --version`): 7.1.30
* Server operating system and version: Red Hat Enterprise Linux Server 7.9

**Comment by gbin2265** [comment]
any news about this problem?

**Comment by kingspeedy95** [comment]
Any news on the problem? We also need the possibility to search for the display_name. Without this feature we cannot use IcingaDB in our production environment.

**Comment by xam-stephan** [comment]
Hello, 2 of 3 controller filters can be extended easily - only for the HostsController I can't find the filter option.

![image](https://github.com/Icinga/icingadb-web/assets/7057845/2c65a701-888c-48d3-a7b1-db12ffa745ec)
![image](https://github.com/Icinga/icingadb-web/assets/7057845/19934825-8a14-4ad6-a01c-e8269b2ed0bd)

**Comment by gbin2265** [comment]
Hello,

thank you for the info because this is the start for searching.

**`what I found`**
--------------------

./library/Icingadb/Web/Controller.php

    protected function prepareSearchFilter(Query $query, string $search, Filter\Any $filter)
    {
        foreach ($query->getModel()->getSearchColumns() as $column) {
            $filter->add(Filter::like(
                $query->getResolver()->qualifyColumn($column, $query->getModel()->getTableName()),
                "*$search*"
            ));
        }
    }

In the default controller, the function prepareSearchFilter will take the default value of getSearchColumns

./library/Icingadb/Model/Service.php
./library/Icingadb/Model/Host.php

    public function getSearchColumns()
    {
        return ['name_ci'];
    }

In the HostsController.php there is no prepareSearchFilter , so it takes the default value name_ci.


**I made these changes and everything works for the global search (for me)**
--------------------------------------------------------------------------------------

./configuration.php
Add to the end of the line &_hostFilterOnly

Line 155:

        $this->provideSearchUrl(
            $this->translate('Hosts'),
            'icingadb/hosts?sort=host.state.severity&limit=10&_hostFilterOnly',
            99
        );


./application/controllers/HostsController.php
Add to the end of the file 

    protected function prepareSearchFilter(Query $query, string $search, Filter\Any $filter)
    {
        if ($this->params->shift('_hostFilterOnly', false)) {
            $filter->add(Filter::like('host.name_ci', "*$search*"));
            $filter->add(Filter::like('host.display_name', "*$search*"));
            $filter->add(Filter::like('host.address', "*$search*"));
        } else {
            parent::prepareSearchFilter($query, $search, $filter);
        }
    }

./application/controllers/ServicesController.php
add these 2 lines to the function prepareSearchFilter

            $filter->add(Filter::like('host.display_name', "*$search*"));
            $filter->add(Filter::like('host.address', "*$search*"));


./application/controllers/TacticalController.php
add these 2 lines to the function prepareSearchFilter


        $filter->add(Filter::like('host.display_name', "*$search*"));
        $filter->add(Filter::like('host.address', "*$search*"));


Hopefully this can be the basis for the changes so that the global search also searches in display_name and address.

**Comment by gbin2265** [comment]
Tested on our test platform and it works.
Now waiting for the official release to put into production.

Thank you !
