### ISSUE TITLE
`contacts` and `contactgroups` not working in deny lists

### ISSUE THREAD

**Issue by dbecker1234** [Icinga/icingadb-web#692]
The "old" monitoring module had a permission "no-monitoring/contacts" to hide globally contacts and contact groups.
That was helpful to restrict the view to provide limited access for other departments for example.

Currently you can see all users/groups on the same named pages and the configured notifications on the host/service objects.
It would be great if something similar to the old behavior will be implemented.

**Comment by nilmerg** [comment]
Hi, have you checked [the documentation on deny lists](https://icinga.com/docs/icinga-db-web/latest/doc/04-Security/#denylists)?

**Comment by dbecker1234** [comment]
Hi, seems I didn't read this part carefully enough... It's working now. :-)

But at least there is a small error in the documentation I think?

> Possible values are: hostgroups, servicegroups, contacts, contactgroups

That's not working, according to configuration.php it's users and usergroups.

**Comment by nilmerg** [comment]
Huh, yes, of course. Will be fixed :sweat_smile:
