### ISSUE TITLE
Filter value "true" and "false"

### ISSUE THREAD

**Issue by madpat1998** [Icinga/icingadb-web#697]
## Describe the bug
I recently migrated our instance to icingadb and as i had to migrate our filters, i had to learn that filters like "Service Is Acknowledged" need to have the value "y" or "n". 
In my opinion this is not the correct behavior as it should be "true" or "false".
There was no suggestion for the value and when i inspected the object the value for "handled" is "false" or "true".

## To Reproduce
1. go to icinadb in icingaweb2
2. click on the service or host overview
3. try to set a filter eg. with "Service Is Acknowledged" = false
4. it will not work
5. find out throu the predefined filter that the correct value would be "n" 

## Expected behavior
Service Is Acknowledged = false
or eg.
Service Is Handled = true
should work or icingaweb should suggest "n" and "y" as correct value.

## Your Environment
* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version	2.11.3
Git commit	f917436a894c1f4148a9c3d6a27f9c20f204e44f
PHP Version	7.3.33
Git commit date	2022-12-14

Loaded Libraries
icinga/icinga-php-library	0.10.1
icinga/icinga-php-thirdparty	0.11.0
Loaded Modules
director		1.9.0
doc			2.11.3
graphite		1.1.0
icingadb		1.0.2
idoreports		0.9.1
incubator		0.19.0
lsd			1.0.1
migrate			2.11.3
monitoring		2.11.3
pdfexport		0.9.1
pr0cinga		1.0.0
reporting		0.9.2
```

* Web browser used: 
google-chrome 108.0.5359.124
* Icinga 2 version used (`icinga2 --version`):
r2.13.6-1
* PHP version used (`php --version`):
7.3.33
* Server operating system and version:
CentOS Linux release 7.9.2009 (Core)

**Comment by nilmerg** [comment]
You can push space on an empty input in the search bar to get some of the available options. This works for any column and for `Service Is Acknowledged` you'd get `y` and/or `n`.

This does not need to change to `true` or `false`. The search bar is new for you and you have to learn a few things first, this is one of them. However, we know that `y` and `n` are not particularly intuitive. This should change to a more appropriate input option in the future.
