### ISSUE TITLE
Symbol doesn't show that Host/Service is in Downtime when it's okay

### ISSUE THREAD

**Issue by winter1967** [Icinga/icingadb-web#706]
Hi,
in the past, using the monitoring module, our admins could see their hosts listed with symbols (a key symbol) when they are in Outage.
It's really nice, because one look and you see, that you can begin the work on the hosts, because it's in downtime.

Now, with the icingadb-web Module, you see in the 'list-view' that the host is in downtime, but ONLY, when it's not in okay state.

**Comment by carraroj** [comment]
ref NC/774865

**Comment by flourish86** [comment]
We should display the downtime icon even for ok states. To indicate, that it doesn’t affect the state, we can make it neutrally gray.

Let’s also add a tool tip for the state visual. This clarifies, what the state means exactly and helps the user learn the different states.

![Frame 3](https://github.com/Icinga/icingadb-web/assets/6977434/e25817a9-6c06-49a5-9267-7b5d1f43e178)
