### ISSUE TITLE
Missing status details

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#72]
## Is your feature request related to a problem? Please describe.
Some details about the status of an object are not shown everywhere or not at all. Below are some suggestions on how to solve what.

### Previous hard state only in history lists

The previous hard state should probably also be shown in the normal lists and the detail view.

**Mockups how this may look like:**
![previous-hard-state-list-left](https://user-images.githubusercontent.com/16668527/80953835-91772100-8dfc-11ea-8905-c50b7805126e.png)
![previous-hard-state-upper-left](https://user-images.githubusercontent.com/16668527/80953826-8cb26d00-8dfc-11ea-9222-ee0443dd46d0.png)

### Flapping state not visible

There's no information that an object is currently flapping other than looking at its history. This should at least be included in the detail view, though no idea where exactly. (@flourish86 Your turn)

### Last state change only as relative date/time

A user would like to be able to copy the exact date and time of the last status change. <sup>1</sup>
To solve this, I have no other idea than exchanging what is shown in the detail view. i.e. Full date/time always, relative time in popup (upper right) (@flourish86 Your opinion please)

### Hostname and Address (ipv4 and ipv6) are not shown

We already have #55 for this, though I'm including it here as well. @flourish86 Please suggest how we'd show these.

## Additional context
¹ https://github.com/Icinga/icingaweb2/issues/4098

**Comment by nilmerg** [comment]
Oh and #47 also mentions a new detail. Seems to be similar to the `check_source`. We should also think of a place where to show this.

**Comment by MaBauMeBad** [comment]
Also it would be nice to have a Number for the check Attempts and not only the little "points".
I think i'm not the only one, who didnt want to count the Points to know where we are standing at this.
(Image max check_attempts 10 or are even more, which we have in use)

**Comment by flourish86** [comment]
> Also it would be nice to have a Number (current/max) for the check Attempts and not only the little "points".
> I think i'm not the only one, who didnt want to count the Points to know where we are standing at this.
> (imagine max check_attempts 10 or are even more, which we have in use)

We totally agree, that the check attempt orbs won't make sense for larger numbers of max checks. We do see the dots better to grasp at a smaller number of max check attempts, though. That's why we display dots at max check attempts up to 5 and show regular numbers when there is more.

**Comment by MaBauMeBad** [comment]
> > Also it would be nice to have a Number (current/max) for the check Attempts and not only the little "points".
> > I think i'm not the only one, who didnt want to count the Points to know where we are standing at this.
> > (imagine max check_attempts 10 or are even more, which we have in use)
> 
> We totally agree, that the check attempt orbs won't make sense for larger numbers of max checks. We do see the dots better to grasp at a smaller number of max check attempts, though. That's why we display dots at max check attempts up to 5 and show regular numbers when there is more.

Thankys for the reply. Is this a new implementation ? Last checked two weeks a go, wasn't it the case and i get 16 dots or whatever max check attempt it is

Thank you ;)

**Comment by flourish86** [comment]
> ### Flapping state not visible
> There's no information that an object is currently flapping other than looking at its history. This should at least be included in the detail view, though no idea where exactly. (@flourish86 Your turn)

Here are some suggestions for the display of flapping list items.

## Similar design as Overdue (The yellow color makes it distinguishable, is kind of random, though)

![Flapping Item badge yellow](https://user-images.githubusercontent.com/6977434/87655933-1ebde680-c759-11ea-97cf-ea39aa60d680.jpg)

## If it makes sense, and there would practically be only two states between which the objects flap, the state visual could also show the previous state

![Flapping Item Badge yellow with double visual](https://user-images.githubusercontent.com/6977434/87657401-1070ca00-c75b-11ea-96af-2ce000368e96.jpg)

## Another way is to make it more subtile and also adjust the overdue design accordingly

![Flapping Timestamp red](https://user-images.githubusercontent.com/6977434/87657151-b5d76e00-c75a-11ea-9dd1-51cc3611db0b.jpg)

**Comment by nilmerg** [comment]
Also related: #181

**Comment by nilmerg** [comment]
We'll show the flapping icon in detailed view mode in the footer. We aren't sure what to do with the previous hard state in the detail view, @flourish86 will prepare some mock ups in order to continue there.

**Comment by flourish86** [comment]
> We'll show the flapping icon in detailed view mode in the footer. We aren't sure what to do with the previous hard state in the detail view, @flourish86 will prepare some mock ups in order to continue there.

### Flapping icon in detailed list item footer.

![Desktop Copy 2](https://user-images.githubusercontent.com/6977434/126452285-59965654-1118-4325-b6be-44953c9a86a3.jpg)

### We discussed two options for the previous hard state in the header

![Desktop Copy 3](https://user-images.githubusercontent.com/6977434/126452735-080b95ee-5e8e-4bc1-82dd-60766d54757c.jpg)

I'd prefer option 2.

### When using option 2 for the the header we should also have the history visuals for soft and hard state changes redesigned

This is how this could look

![Desktop Copy 4](https://user-images.githubusercontent.com/6977434/126452965-cedb5f62-ae24-4cb7-95a2-d7d176f8c476.jpg)

**Comment by nilmerg** [comment]
In the detail area showing the soft state, the previous hard state is small. In the history list showing the soft state changes, the previous hard state is big and the soft state is small. Intended? :thinking:

**Comment by flourish86** [comment]
> In the detail area showing the soft state, the previous hard state is small. In the history list showing the soft state changes, the previous hard state is big and the soft state is small. Intended? 🤔

You're right. Fixed it.

**Comment by nilmerg** [comment]
We've chosen option no. 2 for history lists and the host/service detail view only.
