### ISSUE TITLE
Hide security related data

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb-web#724]
## Describe the bug
The monitoring module had some "Security" tab to hide security related data. I miss this in the icingadb module.

## Screenshots
![passwords](https://user-images.githubusercontent.com/3973350/225321043-99f1f0ac-a112-4b9a-bd15-f0bce15dd88a.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.4
* Web browser: Chrome

**Comment by nilmerg** [comment]
That's a restriction now and mentioned in the [documentation](https://icinga.com/docs/icinga-db-web/latest/doc/10-Migration/#protected-customvars).
