### ISSUE TITLE
Restricted users can't set downtime to multiple hosts

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingadb-web#732]
## Describe the bug
If you try to assign downtime to multiple hosts as a restricted user (see screenshot, user is also restricted to one host group), the following message appears:
```
explode() expects parameter 2 to be string, object given
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Resolver.php(459): explode()
#2 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(264): ipl\Orm\Resolver->qualifyPath()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Authentication/ObjectAuthorization.php(205): ipl\Orm\Query->withColumns()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Authentication/ObjectAuthorization.php(96): Icinga\Module\Icingadb\Authentication\ObjectAuthorization->loadGrants()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/Auth.php(86): Icinga\Module\Icingadb\Authentication\ObjectAuthorization::grantsOnType()
#6 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/CommandActions.php(114): Icinga\Module\Icingadb\Web\Controller->isGrantedOnType()
#7 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/CommandActions.php(127): Icinga\Module\Icingadb\Controllers\HostsController->isGrantedOnCommandTargets()
#8 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/CommandActions.php(218): Icinga\Module\Icingadb\Controllers\HostsController->assertIsGrantedOnCommandTargets()
#9 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(490): Icinga\Module\Icingadb\Controllers\HostsController->scheduleDowntimeAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

This error does not appear for a non-restricted user (admin)

## To Reproduce

1. Click on the hostgroup
2. Select the existing hosts (min. 2 hosts)
3. Click on the right side on Downtime
4. Error appears

## Expected behavior
The same behavios like the non-restricted user

## Screenshots
![image](https://user-images.githubusercontent.com/148245/228167960-b1af4d81-bd50-4333-91ad-bf5a5ab4dc8a.png)

## Your Environment
Icinga DB Web version (System - About): 1.0.2
Icinga Web 2 version (System - About):2.11.4
Web browser: Chrome 110.0.5481.100
Icinga 2 version (icinga2 --version): r2.13.7-1
Icinga DB version (icingadb --version): v1.1.0
PHP version used (php --version): 7.4
Server operating system and version: Debian 10

**Comment by TheCry** [comment]
I have to add something to the bug. We just noticed that.
All actions that you can perform (see screenshot) and select multiple services lead to the "explode" error. 
![image](https://user-images.githubusercontent.com/148245/230316825-f5464f59-5cbd-4d50-b051-bcd35bcdff84.png)

**Comment by TheCry** [comment]
Good morning. By coincidence, a colleague tested the function this morning. Apparently it works again as a restricted user. Now we have checked what updates have been installed in the last few days. Here we then identified "icinga-php-library". Is it possible that this has fixed the error?

**Comment by nilmerg** [comment]
Yes. I just forgot to mention this here. :+1:
