### ISSUE TITLE
Partition/disk sizes are calculated incorrectly

### ISSUE THREAD

**Issue by knbrende** [Icinga/icingadb-web#738]
## Describe the bug
The partition and disk sizes shown in "Performance Data" aren't calculated correctly.
In Icingaweb2 all values are identical to the system output.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Run check_disk plugin/command on a system with big enough disks (it's more obvious starting with partitions bigger than 1TB).
2. Compare the output under "Performance Data" in Icingadb-web and Icingaweb2.

## Expected behavior
Having partition/disk sizes identical to the system output or Icingaweb2

### check_disk:

`df -h` on server
![image](https://user-images.githubusercontent.com/80825106/230056689-24038a12-cd9b-4bb5-8779-908793e48f7e.png)

Output Icingaweb2
![image](https://user-images.githubusercontent.com/80825106/230055129-09d6d3c3-f63d-4b0f-acbe-ffef64418398.png)

Output Icingadb-web
![image](https://user-images.githubusercontent.com/80825106/230055444-b1f91a05-4ed7-46cf-b809-268b22b9fcb9.png)

### custom plugin to check xfs quotas
Output on system
![image](https://user-images.githubusercontent.com/80825106/230056014-3677645a-baf7-4477-a6bb-92525ab3325e.png)

Output Icingaweb2
![image](https://user-images.githubusercontent.com/80825106/230056111-30662276-a946-4fa7-8a9b-7dc9c69f87ec.png)

Output Icingadb-Web
![image](https://user-images.githubusercontent.com/80825106/230056254-37a4c7ab-ac24-4326-89fa-91478622fe64.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.3
* Web browser: Chrome 111.0.5563.147
* Icinga 2 version (`icinga2 --version`): 2.13.7
* Icinga DB version (`icingadb --version`): 1.1.0
* PHP version used (`php --version`): 8.0.28
* Server operating system and version: SUSE Linux Enterprise Server 15 SP4

**Comment by knbrende** [comment]
Hi, here a screenshot of the output:

![image](https://user-images.githubusercontent.com/80825106/231427635-782d35e9-4764-4e82-9cb9-ba08f7699b41.png)


And here a copy&paste of the output:

`DISK OK - free space: / 170782 MB (80.45% inode=100%); /boot 678 MB (66.93% inode=100%); /data 157311637 MB (66.53% inode=98%);| /=41478MB;169808;191034;0;212260 /boot=335MB;811;912;0;1014 /data=79106752MB;189134712;212776551;0;236418390`

**Comment by raviks789** [comment]
@knbrende the issue is due to the `check_disk` monitoring plugin which still uses the old unit MB to represent megabytes 'binary' instead of MiB. There already exists an issue for this in monitoring plugins repo (refer: https://github.com/monitoring-plugins/monitoring-plugins/issues/1786).

**Comment by RincewindsHat** [comment]
Actually, in current versions of the monitoring plugins this is not a problem since perfdata are printed in Bytes anyway.
So this is either a [nagios-plugins](https://github.com/nagios-plugins/nagios-plugins) problem (e.g. RHEL based distributions) or just an old version.

**Comment by RincewindsHat** [comment]
This is a problem of the [nagios-plugins](https://github.com/nagios-plugins/nagios-plugins), not the [monitoring plugins](https://github.com/monitoring-plugins/monitoring-plugins) (where I change the perfdata output).
This is a little bit besides the point, but important to me :-)

Apart from that, yes, IcingaDB seems to use SI units by default (not my favourite), but the numbers seem to be correct (given the whole `* 1024^2 / 1000^3` + rounding process).

**Comment by knbrende** [comment]
Thanks for the clarification. Until now I was under the impression all RHEL based distros only use the old name for compatibility reasons. I wasn't aware Nagios Plugins are still a thing.

Is it useful to use SI units for disk/partition sizes? I personally don't know of any recent OS not using binary values.
I also haven't found a way to change this behavior in our installation.

**Comment by RincewindsHat** [comment]
It would indeed be nice to have a configuration option for that.

**Comment by nilmerg** [comment]
What are you talking ... about? Icinga DB Web doesn't use SI units. The monitoring module does.

**Comment by RincewindsHat** [comment]
@nilmerg I would like to disagree kindly. At least my Icinga db web does show me SI units

**Comment by nilmerg** [comment]
Oh well, it's late. And I generally get confused when talking about SI units...
