### ISSUE TITLE
host/service view like hostgroup/servicegroup

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#763]
Hello,

has the question ever been asked, or is this already possible and I don't see it,
to have a view with the look like overview->HostGroup/ServiceGroup that gives the list of

- every host with the number of services and status (x times crit/ x times warning/...)
![host](https://github.com/Icinga/icingadb-web/assets/29303758/b6a582ee-83a9-4c1e-a037-96a50020b2b6)

- every service with the number of hosts with and status (x times crit/ x times warning/...)
![service](https://github.com/Icinga/icingadb-web/assets/29303758/e0e397ad-f7d4-4b16-8afa-67cd4ff1d6ee)

It would also be useful if we could reuse this link in our dashboard
but with an extra filter that only makes the critical  or critcal/warning visible.

In this example for host critical is this only the first line
![host_critical](https://github.com/Icinga/icingadb-web/assets/29303758/c506ce81-8020-4fb6-b018-e005913568ed)

In this example for service critical is this only
![servicecritical](https://github.com/Icinga/icingadb-web/assets/29303758/fd6d7565-07ce-48f6-96d7-b6556272ae81)

What I do now is create servicegroups with one service in, or hostgroups with 1 host in for the most important services/hosts.

For example, we can direct make visible to our operator room which hosts or services have problems en not like the tactical view 
that you see that there are errors but that you first have to select to see who has problems.

regards,
Geert

**Comment by nilmerg** [comment]
> every host with the number of services and status (x times crit/ x times warning/...)

There is #707 for this.

> every service with the number of hosts with and status (x times crit/ x times warning/...)

That doesn't make sense. There is only a single host per service.
