### ISSUE TITLE
Documentation look strange 

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingadb-web#774]
## Describe the bug
The Installation part of the doc looks strange

## Screenshots
<img width="391" alt="2023-06-05 16_01_54-Icinga Web" src="https://github.com/Icinga/icingadb-web/assets/29682206/e144660c-8f76-478c-b89e-99a0bdb3e12c">

## Cause
`
# Installing Icinga DB Web`

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.4
* PHP version used (`php --version`): 7.4
* Server operating system and version: Ubuntu 20.04

**Comment by nilmerg** [comment]
Hey, the documentation here isn't compatible with the documentation module, I'm afraid. This probably also won't change, so I'll close here.
