### ISSUE TITLE
Division by zero error for host in soft_state 99

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#788]
Hello,

## Environment snapshot 24Jun2023
I upgraded to the latest snapshot of 24Jun2023.
Version : 
icinga-cube.noarch                    1.3.0+1.g8ecdf08-1687561408.el7      
icinga-cube-web.noarch                1.3.0+1.g8ecdf08-1687561408.el7      
icinga-l10n.noarch                    1.2.0+115.g66b6ada-1687554256.el7    
icinga-php-common.noarch              1.0.0165655404400000000-0.20220630.0154.el7.icinga
icinga-php-library.noarch             0.12.0+3.g2ae9c91-1687554236.el7     
icinga-php-thirdparty.noarch          0.11.0+9.g67bb5a3-1687554268.el7     
icinga2.x86_64                        2.13.7+751.geddd4c7bf-1687557815.el7 
icinga2-bin.x86_64                    2.13.7+751.geddd4c7bf-1687557815.el7 
icinga2-common.x86_64                 2.13.7+751.geddd4c7bf-1687557815.el7 
icingacli.noarch                      2.11.4+111.gdb9888b1f-1687557814.el7 
icingadb-web.noarch                   1.0.2+82.g67fc7f5-1687561409.el7     
icingaweb2.noarch                     2.11.4+111.gdb9888b1f-1687557814.el7 
icingaweb2-common.noarch              2.11.4+111.gdb9888b1f-1687557814.el7 
icingaweb2-vendor-HTMLPurifier.noarch 1:2.11.4+111.gdb9888b1f-1687557814.el7
icingaweb2-vendor-JShrink.noarch      2.11.4+111.gdb9888b1f-1687557814.el7 
icingaweb2-vendor-Parsedown.noarch    2.11.4+111.gdb9888b1f-1687557814.el7 
icingaweb2-vendor-dompdf.noarch       2.11.4+111.gdb9888b1f-1687557814.el7 
icingaweb2-vendor-lessphp.noarch      2.11.4+111.gdb9888b1f-1687557814.el7 
icingaweb2-vendor-zf1.noarch          2.11.4+111.gdb9888b1f-1687557814.el7 
php-icinga.noarch                     2.11.4+111.gdb9888b1f-1687557814.el7 

## Describe the bug
When I open a host listed at host.state.soft_state=99 then I get a Division by zero error.
Only for soft state 99 I have the error.

## To Reproduce
list :  http://x.x.x.x/icingaweb2/icingadb/tactical#!/icingaweb2/icingadb/hosts?host.state.soft_state=99
Open one in the list.

## This is the error 
Error: 
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/CheckStatistics.php(127): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/Card.php(24): Icinga\Module\Icingadb\Widget\Detail\CheckStatistics->assembleBody(Object(ipl\Html\HtmlElement))
#2 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/Card.php(55): ipl\Web\Common\Card->createBody()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/CheckStatistics.php(355): ipl\Web\Common\Card->assemble()
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(344): Icinga\Module\Icingadb\Widget\Detail\CheckStatistics->assemble()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(566): ipl\Html\HtmlDocument->ensureAssembled()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\HtmlDocument->renderUnwrapped()
#16 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#19 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(466): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#20 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#24 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#25 {main}

This is the line 127 in CheckStatistics.php
$leftExecutionEnd = $nextCheckTime !== null ? $durationScale * ( 1 - ($nextCheckTime - $executionEndTime) / ($nextCheckTime - $lastUpdateTime) ) : 0;

regards,
Geert

**Comment by nilmerg** [comment]
If you can still reproduce this, please show the details of the source tab, if it's accessible: `/icingaweb2/icingadb/host/source?name=<host-name>`

**Comment by gbin2265** [comment]
Source Location
You can find this object in /var/lib/icinga2/api/zones/satelite12-00.dns.be/_etc/host/xxx/xxx/xxx/xxx.xxx.xxx.xxx.conf on line 11.
Object Attributes
acknowledgement	0
acknowledgement_expiry	n. a.
acknowledgement_last_change	 n. a.
action_url	 n. a.
address	"x.x.x.x"
address6	 n. a.
check_attempt	1
check_command	"hostalive4"
check_interval	1.00 m
check_period	 n. a.
check_timeout	 n. a.
command_endpoint	 n. a.
downtime_depth	0
enable_active_checks	true
enable_event_handler	true
enable_flapping	false
enable_notifications	true
enable_passive_checks	false
enable_perfdata	true
event_command	 n. a.
executions	 n. a.
flapping	false
flapping_current	0
flapping_ignore_states	 n. a.
flapping_last_change	n. a.
flapping_threshold	0
flapping_threshold_high	30
flapping_threshold_low	25
force_next_check	false
force_next_notification	false
groups	

[
    "hostgroup_all_linux",
    "vars_tst_usergroup_dba"
]
handled	false
icon_image	 n. a.
icon_image_alt	n. a.
last_check	1969-12-31T23:59:59.000+00:00
last_hard_state	down
last_hard_state_change	n. a.
last_reachable	true
last_state	down
last_state_change	n. a.
last_state_down	n. a.
last_state_type	0
last_state_unreachable	n. a.
last_state_up	n. a.
max_check_attempts	3
next_check	2023-06-26T13:34:28.811+00:00
next_update	2023-06-26T13:35:28.811+00:00
notes	n. a.
notes_url	"http://wiki.dns.be/mediawiki/index.php?title=$host.name$"
original_attributes	n. a.
previous_state_change	n. a.
problem	false
retry_interval	30.00 s
severity	16
state	down
state_type	0
vars	

{
    "command_endpoint_host": "",
    "geolocation": "50.93490305,4.033844827662721",
    "tst_check_host_linux": "1",
    "tst_comment": {
        "tst_comment_xxx_virtops": {
            "dummy_state": 0,
            "dummy_text": "xxx VIRTOPS"
        },
        "tst_hostname_x.x.x.x_y.dns.be": {
            "dummy_state": 0,
            "dummy_text": "IP : x.x.x.x - Hostname/Alias : y.dns.be"
        },
        "tst_unit_code_5440": {
            "dummy_state": 0,
            "dummy_text": "IP : x.x.x.x - Unit Code : 5440"
        }
    },
    "notification": {
        "notifall": {
            "groups": [
                "icingaadmins"
            ]
        }
    },
    "os": "rhel5",
    "sla": "24x7",
    "sshcheck": "0"
}
volatile	false
zone	"satelite12-00.dns.be"
Custom Variables
command_endpoint_host	
empty string
geolocation	50.93490305,4.033844827662721
tst_check_host_linux	1
tst_comment	3 items
tst_comment_x_virtops	2 items
dummy_state	0
dummy_text	x VIRTOPS
tst_hostname_x.x.x.x_y.dns.be	2 items
dummy_state	0
dummy_text	IP : x.x.x.x - Hostname/Alias : y.dns.be
tst_unit_code_5440	2 items
dummy_state	0
dummy_text	IP : x.x.x.x - Unit Code : 5440
tst_gsbgroup_5440	1
tst_hostname	y.dns.be
tst_ip	x.x.x.x
tst_ip_long	xxx.xxx.xxx.xxx
tst_linux_os	redhat
tst_release_major	5
tst_release_minor	11
tst_server_ip_ops	x.x.x.x
tst_server_second_ip_ops	1
tst_server_type_cluster_service	1
tst_serverenvironment_dev_tst_acc_trg_prd_tier	none
tst_shorthostname	xxxx
tst_tier	0
tst_usergroup_dba	1
tst_var_ldap_uri	ldap://x.x.x.x:389/
ip_level_00	ip_range_root
ip_level_01	ip_range_012
ip_level_02	ip_range_012_042
ip_level_03	ip_range_012_042_031
ip_range_012	1
ip_range_012_042	1
ip_range_012_042_031	1
notification	1 item
notifall	1 item
groups (Array)	1 item
[0]	icingaadmins
os	rhel5
sla	24x7
sshcheck	0
Volatile State Details
check_attempt	1
check_timeout	1.00 m
hard_state	pending
host_id	"a0e0db839a333939b6b96a6bd6bc5d8ac010b2c3"
in_downtime	false
is_acknowledged	0
is_active	true
is_flapping	false
is_handled	false
is_problem	false
is_reachable	true
last_state_change	
n. a.
next_check	2023-06-26T13:34:22.841+00:00
next_update	2023-06-26T13:35:22.841+00:00
previous_hard_state	pending
previous_soft_state	pending
severity	16
soft_state	99
state_type	1

**Comment by gbin2265** [comment]
Thank you for taking a look.

These are tests on our test platform, which means that not every check can be done and that it is in a soft state.
But even then I would think, as this was before the upgrade, I can see the details of the host.

regards,
Geert

**Comment by nilmerg** [comment]
Reproduced it! Thanks for the feedback :)
