### ISSUE TITLE
Icon image support

### ISSUE THREAD

**Issue by distahl** [Icinga/icingadb-web#79]
## Describe the bug
Icons defined in host objects (see below) or service objects are not getting displayed in icingadb.
```
object Host "SomeName" {
    [...]
    icon_image = "img/icons/base/switch-gold.png"
    [...]
}
```

Am I doing something wrong or is this not implemented?

## To Reproduce
Define icon_image, reload icinga2 and have a look into icingadb-web

## Expected behavior
Display Icons in front of device name. Same as in monitoring module.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 5th May 2020 - Commit: 007646a16aa4bdbda80f494c9ba02f5d6d3f9026
* Icinga Web 2 version (System - About): 2.8.0-rc1
* Web browser: Chromium v80
* Icinga 2 version (`icinga2 --version`): 2.12.0-0.rc1.1
* Icinga DB version (`icingadb --version`): v1.0.0-rc1
* PHP version used (`php --version`): 7.1.30
* Server operating system and version: CentOS Linux release 7.8.2003 (Core)

**Comment by nilmerg** [comment]
That's not implemented. I don't know why or what the plans are here though, maybe @flourish86 does?

**Comment by flourish86** [comment]
We plan to implement it. But we have to find a way to handle different image aspect ratios and sizes without breaking the layout.

**Comment by flourish86** [comment]
@distahl Is there a change you could provide us some of the icons you use, so we can experiment a little and make sure your icons will work?

**Comment by distahl** [comment]
Sure. Here they are:
[icons.zip](https://github.com/Icinga/icingadb-web/files/4628462/icons.zip)

**Comment by flourish86** [comment]
Thanks. 😊

**Comment by nilmerg** [comment]
@flourish86 Did this already lead to any conclusion?
