### ISSUE TITLE
Timezone on source page not correct

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#800]
## Describe the bug
Is it possible that the time zone is not active on the source page .?
I do the check here in Brussels on 2023-07-07 21:28 and the source page give me 2h earlier.

## My TimeZone 
When I go to an event in the history page, the date/time is correct in my timezone (europe/brussels)
If you are going to look with the 

- datetimectl ->
Time zone: Europe/Brussels (CEST, +0200)

- php -i | grep time zone ->
Default time zone => Europe/Brussels
date.timezone => Europe/Brussels => Europe/Brussels

- If you go into the user config it is also on
Your Current Timezone : Europe/Brussels

You see the time zone is correct everywhere.

## Check I do 
- I put a host in downtime schedule
- I stopped the schedule downtime
- I go to check the history that the event stop schedule downtime

Downtime cancelled by author
Entered On 2023-07-07 21:28:30
Cancelled On 2023-07-07 21:28:58

! The date/time is correct on the page

- I go to the host and started the check (ping)
- I go direct to the source page and checked the date/time for 

execution_start	2023-07-07T19:28:39.966+00:00
schedule_end	2023-07-07T19:28:43.978+00:00

! here you see that the date is 2h earlier than what is now in my country

- I then requested the info from the host via the API and convert the  EPOCH format to date/time format.
"execution_start": 1688758182.448638, # date --date='@1688758182.448638' Fri Jul  7 21:29:42 CEST 2023
"schedule_end": 1688758186.464043,    # date --date='@1688758186.464043' Fri Jul  7 21:29:46 CEST 2023

! Here you can see that after conversion of the EPOCH gives the correct date/time in my zone.

## what I think
Is it correct that I think the source page is not converted to my timezone for the date/time fields?

## Your Environment
See here the versions i running -> latest snapshot on 8jul2023-01:25 for centos 7

On the Master/satellite
icinga2-2.13.7+780.g2e4af46d4-1688767414.el7.x86_64
icinga2-bin-2.13.7+780.g2e4af46d4-1688767414.el7.x86_64
icinga2-common-2.13.7+780.g2e4af46d4-1688767414.el7.x86_64
icinga2-ido-pgsql-2.13.7+780.g2e4af46d4-1688767414.el7.x86_64
icingadb-1.1.0.4.g4ed4db3-0.20230120.2003.el7.icinga.x86_64
icingadb-redis-7.0.5-0.20230707.1804.el7.icinga.x86_64
icingadb-redis-debuginfo-7.0.5-0.20230707.1804.el7.icinga.x86_64
icingadb-redis-devel-7.0.5-0.20230707.1804.el7.icinga.x86_64
vim-icinga2-2.13.7+780.g2e4af46d4-1688767414.el7.x86_64

On the IcingaWeb2
icingacli-2.11.4+123.gd31100508-1688767412.el7.noarch
icinga-cube-1.3.1+0.gf259240-1688771009.el7.noarch
icinga-cube-web-1.3.1+0.gf259240-1688771009.el7.noarch
icingadb-web-1.0.2+102.g86b5071-1688771009.el7.noarch
icinga-l10n-1.2.0+117.g52ee975-1688763810.el7.noarch
icinga-php-common-1.0.0165655404400000000-0.20220630.0154.el7.icinga.noarch
icinga-php-library-0.12.0+3.gf6f63ae-1688763829.el7.noarch
icinga-php-thirdparty-0.11.0+9.g1847a7b-1688763820.el7.noarch
icingaweb2-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-common-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-vendor-dompdf-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-vendor-HTMLPurifier-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-vendor-JShrink-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-vendor-lessphp-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-vendor-Parsedown-2.11.4+123.gd31100508-1688767412.el7.noarch
icingaweb2-vendor-zf1-2.11.4+123.gd31100508-1688767412.el7.noarch
php-icinga-2.11.4+123.gd31100508-1688767412.el7.noarch

regards,
Geert

**Comment by nilmerg** [comment]
Hi,

the intention of the *Source* tab is to show the original *source* data from which everything else in the remaining UI is derived from. So yeah, it does not include your timezone on purpose. Nor is anything translated or otherwise internationalized, if you wondered.

**Comment by sebek72** [comment]
Is there a way to control the API date format?
I have an issue that the API timestamps are formatted wrong and the nagstamon app cannot digest.
https://github.com/HenriWahl/Nagstamon/issues/962

JSON output: last_update":"2023-09-26T10:29:16.935+00:00"
