### ISSUE TITLE
Hostgroups/Servicegroups/tactical SQL grouping error for != search

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#815]
Hello,

## Describe the bug
I just wanted to show the hostgroups/servicegroups with an error.
I do an unlike search for this on the soft state and I get an SQL error.

In this version the != works perfectly
icingadb-web-1.0.2+102.g86b5071-1688771009.el7.noarch

In this version I have the error
icingadb-web-1.0.2+142.gcd5f74b-1689980814.el7.noarch

## To Reproduce
* HOSTGROUPS

http://x.x.x.x/icingaweb2/icingadb/servicegroups?service.state.soft_state!=0

SQLSTATE[42803]: Grouping error: 7 ERROR: column "sub_service_state_service_servicegroup.id" must appear in the GROUP BY clause or be used in an aggregate functio

* SERVICEGROUPS

http://x.x.x.x/icingaweb2/icingadb/servicegroups?service.state.soft_state!=0

SQLSTATE[42803]: Grouping error: 7 ERROR: column "sub_service_state_service_servicegroup.id" must appear in the GROUP BY clause or be used in an aggregate function

* TACTICAL

http://x.x.x.x/icingaweb2/icingadb/tactical?service.state.is_overdue&service.name!=test_%2A

SQLSTATE[42803]: Grouping error: 7 ERROR: column "sub_service_host.id" must appear in the GROUP BY clause or be used in an aggregate function

## Your Environment
See here the versions i running :
icinga2 is version 2.14
icingadb/web latest snapshot on 2023-07-22 05:30 for centos 7

vim-icinga2-2.14.0-1.el7.x86_64
icinga2-ido-pgsql-2.14.0-1.el7.x86_64
icinga2-common-2.14.0-1.el7.x86_64
icinga2-bin-2.14.0-1.el7.x86_64
icinga2-2.14.0-1.el7.x86_64

icingadb-1.1.0.4.g4ed4db3-0.20230120.2003.el7.icinga.x86_64

icingadb-redis-7.0.5-0.20230721.1804.el7.icinga.x86_64
icingadb-redis-devel-7.0.5-0.20230721.1804.el7.icinga.x86_64
icingadb-redis-debuginfo-7.0.5-0.20230721.1804.el7.icinga.x86_64

icingadb-web-1.0.2+142.gcd5f74b-1689980814.el7.noarch

icinga-cube-1.3.1+0.gf259240-1689980803.el7.noarch
icinga-cube-web-1.3.1+0.gf259240-1689980803.el7.noarch
icinga-l10n-1.2.0+124.g557eb59-1689973425.el7.noarch
icinga-php-common-1.0.0165655404400000000-0.20220630.0154.el7.icinga.noarch
icinga-php-library-0.12.0+3.gc28e105-1689973411.el7.noarch
icinga-php-thirdparty-0.11.0+12.g5844bdf-1689973454.el7.noarch
icingacli-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-common-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-vendor-HTMLPurifier-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-vendor-JShrink-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-vendor-Parsedown-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-vendor-dompdf-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-vendor-lessphp-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
icingaweb2-vendor-zf1-2.11.4+124.g4ccebb78b-1689977011.el7.noarch
php-icinga-2.11.4+124.g4ccebb78b-1689977011.el7.noarch

regards,
Geert

**Comment by nilmerg** [comment]
Thanks for reporting this. Missed this during my testing :roll_eyes:
