### ISSUE TITLE
Disabling active checks via feature command switch not visible in list view

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingadb-web#868]
## Describe the bug
When disabling active checks of a host or service it is not visible in the list views for hosts or services.

## To Reproduce
Disable active checks via feature command switch
![image](https://github.com/Icinga/icingadb-web/assets/24474580/9982f4b0-6ac0-4d49-ab65-d6ab61ce5366)
![image](https://github.com/Icinga/icingadb-web/assets/24474580/bad45a58-b749-4a85-a31a-7644fd828a9c)
![image](https://github.com/Icinga/icingadb-web/assets/24474580/786bf126-2656-431c-a056-ba4cab40dea6)

## Expected behavior
Some form of icon/information is visible, e.g. like it was in the "old" webinterface with the icon
![image](https://github.com/Icinga/icingadb-web/assets/24474580/f85032c4-d8eb-4641-8446-a1af3d4da6cd)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.4
* Web browser: Edge/Vivaldi/Chrome
* Icinga 2 version (`icinga2 --version`): 2.13.7
* Icinga DB version (`icingadb --version`): 1.1.1
* PHP version used (`php --version`): 7.2.24
* Server operating system and version: rhel8

**Comment by nilmerg** [comment]
You should switch to the detailed list layout.

**Comment by log1-c** [comment]
@nilmerg 
imo this should always be visible, not only in the detailed view, as it is critical information.
Also I can't find a way to set the detailed view as a default. How can this be done?

Additionally the contrast of the icon against its background is not good  in both light and dark mode 
![image](https://github.com/Icinga/icingadb-web/assets/24474580/a441d74e-6525-4b41-8076-d5d4cb0b9ff8)
![image](https://github.com/Icinga/icingadb-web/assets/24474580/061391af-8325-4def-8db0-2221f360d674)
and worsens when the entry is selected
![image](https://github.com/Icinga/icingadb-web/assets/24474580/b0933d6c-f5fb-4ef6-b3b9-d25b99270b48)
![image](https://github.com/Icinga/icingadb-web/assets/24474580/111f855a-e11f-4426-9ffb-a1fff50556be)

**Comment by nilmerg** [comment]
> Also I can't find a way to set the detailed view as a default. How can this be done?

Once you switch the layout, it stays like this in the same view as long as you don't log out.

> Additionally the contrast of the icon against its background is not good in both light and dark mode

Yeah, please create a new issue.
