### ISSUE TITLE
Filters do not show columns in dashboards in full screen mode

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icingadb-web#873]
## Describe the bug
If you use the filter in `icingadb/hosts` or `icingadb/servces`, you will properly get a list with several columns. 
When you add it to a dashboard, you "lose" the columns and get only the object output. 
Now you can zoom into your window and see the columns you have in your filter.

In my opinion, it should be the other way round. When you are in full screen mode, you should see all the columns and when you zoom in, the columns should disappear.

Fullscreen:
![fullscreen](https://github.com/Icinga/icingadb-web/assets/44896393/a02bb98d-3409-4165-a7e3-2e968278c8f3)

Smaller window:
![smaller-screen](https://github.com/Icinga/icingadb-web/assets/44896393/29985b92-e88e-47c5-aefe-fe9ae1aee85b)

Also it would be nice, if this would be configurable. So the user can decide what he wants.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.4

**Comment by nilmerg** [comment]
Already fixed by #759
