### ISSUE TITLE
Multiple variables won't be evaluated in one field

### ISSUE THREAD

**Issue by adaevitncar** [Icinga/icingadb-web#885]
## Describe the bug
Using the "old" monitoring module we use the field "notes_url" to link to a wikipage with the following content:

notes_url = "http://<HOSTNAME>/dokuwiki/doku.php?id=<REPLACE>:<REPLACE>:<REPLACE>:$host_display_name$:$display_name$"

which will be correctly converted to e.g.

http://<HOSTNAME>/dokuwiki/doku.php?id=<REPLACE>:<REPLACE>:<REPLACE>:foreman-client-01.vrc.lan:sw_remote_http_80

So both variables (host_display_name and display_name) are evaluated fine. The same does not work using icingadb-web. Only the last variable is evaluated. 

## To Reproduce

1. Create a service template which configures the notes url using the variables shown above
2. Apply the template to a service
3. Verify variable evaluation in "old" monitoring 
4. Compare evaluation in icingadb-web

## Expected behavior

Both variables should be evaluated like it's in the "old" monitoring.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.4
* Web browser: Firefox/Chrome/...
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Icinga DB version (`icingadb --version`): v1.1.1
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Debian GNU/Linux 11 (bullseye)

**Comment by yhabteab** [comment]
Hii @adaevitncar, thanks for reporting. In order to work this in Icinga DB Web, you have to change this variable `$host_display_name$` to `$host.display_name$`.

**Comment by adaevitncar** [comment]
This will break the simultaneous usage of the existing monitoring module and icingadb-web.

Any ideas how to achieve the simultaneous usage?
