### ISSUE TITLE
Redirection loop in global search

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#887]
Hello,

we have upgraded icingaweb2 to version 2.12
We only have the icingadb/icingadb-web running, and no longer the monitoring module.

## Describe the bug
If we then do a global search for an IP and then go to the detail "tactical overview: <IP>",
then it creates a URL that is more than 6900 characters long and stop working. 

## Result
He repeats the same thing over and over again :

`http://site.com/icingaweb2/icingadb/tactical?service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&service.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.name_ci~%2Ax.x.x.x%2A|service.host.display_name~%2Ax.x.x.x%2A|service.host.address~%2Ax.x.x.x%2A|service.host.address6~%2Ax.x.x.x%2A&q=x.x.x.x
`

## Question 
Is this a problem for icingadb-web or for icingaweb2?

## Your Environment
icinga-cube-web.noarch                 1.3.2-1.el7                     
icinga-cube.noarch                     1.3.2-1.el7                     
icinga-l10n.noarch                     1.3.0-1.el7                     
icinga-php-common.noarch               1.0.0165655404400000000-0.20220630.0154.el7.icinga
icinga-php-library.noarch              0.13.0-1.el7                    
icinga-php-thirdparty.noarch           0.12.0-1.el7                    
icinga2-bin.x86_64                     2.14.0-1.el7                    
icinga2-common.x86_64                  2.14.0-1.el7                    
icinga2-ido-pgsql.x86_64               2.14.0-1.el7                    
icingacli.noarch                       2.12.0-1.el7                    
icingadb-web.noarch                    1.0.2+243.gde96826-1694819007.el7 
icingaweb2-common.noarch               2.12.0-1.el7                    
icingaweb2.noarch                      2.12.0-1.el7                    
php-icinga.noarch                      2.12.0-1.el7

**Comment by nilmerg** [comment]
> Is this a problem for icingadb-web or for icingaweb2?

Icinga DB Web :cold_sweat:

**Comment by nilmerg** [comment]
Thank you for reporting! We would have missed this for sure :neutral_face:
