### ISSUE TITLE
Admins can only see objects they have explicit rights for since icingaweb 2.12.0

### ISSUE THREAD

**Issue by xschlef** [Icinga/icingadb-web#888]
## Describe the bug
We upgraded icingaweb2 to 2.12.0 and are now unable to list all objects for users with admin privileges.

## To Reproduce
The normal monitoring plugin displays all hosts for admins (Administrative Access = True). The icingadb-web module will only display objects the the user was explicitly granted access to. If you can somehow navigate to other hostgroups, you will see hosts / services that you don't see in the normal dashboard and you can access them.

1. Install icingaweb2 and icingadb-web
2. create an admin group and grant access to everything
3. create groups of objects that a user / group has access to
4. icingadb-web will only display members of those groups, while the standard monitoring plugin will display all hosts/objects

## Expected behavior
Admins should be able to see all hosts unless the rights have been removed.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2-1+debian11
* Icinga Web 2 version (System - About): 2.12.0-1+debian11
* Web browser: Firefox 118
* Icinga 2 version (`icinga2 --version`): 2.14.0-1+debian11 
* Icinga DB version (`icingadb --version`): 1.1.1-1+debian11 
* PHP version used (`php --version`): 8.1
* Server operating system and version: Debian 11

## Additional context
We are using external auth through kerberos with ldap integration.

**Comment by nilmerg** [comment]
Hi,

> create groups of objects that a user / group has access to

I think you mean that you restrict the user/group per role restriction to specific host-/service-groups, correct?

> icingadb-web will only display members of those groups, while the standard monitoring plugin will display all hosts/objects

Then is, what Icinga DB Web does, correct. The monitoring module may simply show all objects, as the restriction you configured for Icinga DB Web doesn't apply there.

**Comment by xschlef** [comment]
Sorry not being precise.

Let's say we have two roles defined in our roles.ini:
```
# user1 and user2 are members of the admins group
[admins]
groups = "admins"
permissions = "*"
monitoring/filter/objects = "host_name=*"
icingadb/filter/objects = "host.name=*"
icingadb/protect/variables = "*pw*,*pass*,*community*"

# automatic hostgroup based roles our configmanagement creates
[hostgroup-xxx]
users = "user1,user2"
permissions = "application/share/navigation, module/doc, module/grafana, grafana/graphconfig, grafana/graph, grafana/showall, grafana/enablelink, module/monitoring, monitoring/command/schedule-check, monitoring/command/acknowledge-problem, monitoring/command/remove-acknowledgement, monitoring/command/comment/*, monitoring/command/downtime/*, module/icingadb, icingadb/command/schedule-check, icingadb/command/acknowledge-problem, icingadb/command/remove-acknowledgement, icingadb/command/comment/*, icingadb/command/downtime/*"
monitoring/filter/objects = "hostgroup_name=hostgroup-xxx"
icingadb/filter/objects = "hostgroup.name=hostgroup-xxx"
icingadb/protect/variables = "*pw*,*pass*,*community*
```

with icingadb with the newest icingaweb2, I will only be able to see what is definied for hostgroup-xxx. I may still access other objects if I have a link for them or know their name, but I will not see the objects in the standard overview.

This behavior just started with icingaweb2 2.12.0. The monitoring plugin still show all objects in the standard overview pages.

**Comment by nilmerg** [comment]
> monitoring/filter/objects = "host_name=*"
> icingadb/filter/objects = "host.name=*"

Instead of this, you should use `unrestricted = 1`. It has the same effect and is the recommended way since v2.9.0.

For more information though, please have a look [here](https://github.com/Icinga/icingadb-web/issues/896).

**Comment by xschlef** [comment]
Thanks for clarification. Switched to the new wildcard syntax "~" and everything works again.
