### ISSUE TITLE
Host details page not working since upgrade to 1.1.0

### ISSUE THREAD

**Issue by scriptkiddy666** [Icinga/icingadb-web#900]
## Describe the bug
Since the upgrade to the new version 1.1.0 of IcingaDB Web the host overview page doesn't work anymore and only an error message is displayed.

![2023-10-02 08_53_07-REZ01SR0266 - rez01sr0266 patrizia ag - Remotedesktopverbindung](https://github.com/Icinga/icingadb-web/assets/11939952/0dc79a67-95a7-4d08-880f-e51275a9e7b1)

However the details page of services still works and the new feature (execution start/end time) is also shown.
(I can click on the service itself in the Overview -> Services pane.)

## To Reproduce
Update to IcingaDB Web via apt update & apt upgrade.
(No other updates were available in my case, so it's really only the icingadb-web package.)

## Expected behavior
No error message should appear and the details page should work like before.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.0 (before 1.0.2)
* Icinga Web 2 version (System - About): 2.12.0
* Web browser: Microsoft Edge (latest)
* Icinga 2 version (`icinga2 --version`):  r2.14.0-1
* Icinga DB version (`icingadb --version`): v1.1.1
* PHP version used (`php --version`): 8.1.2-1ubuntu2.14
* Server operating system and version: Ubuntu 22.04.3 LTS

## Additional context
There are no outstanding migrations in the new System -> Migrations pane. (Neither before nor after the update.)
A system reboot doesn't help either.

**Comment by gbin2265** [comment]
Same problem with rhel 7.9 & chrome. 

icingadb-web.noarch                    1.1.0-1.el7 
icingaweb2-common.noarch               2.12.0-1.el7
icingaweb2.noarch                      2.12.0-1.el7
php-icinga.noarch                      2.12.0-1.el7
icinga-cube-web.noarch                 1.3.2-1.el7
icinga-cube.noarch                     1.3.2-1.el7
icinga-l10n.noarch                     1.3.0-1.el7
icinga-php-common.noarch               1.0.0165655404400000000-0.20220630.0154.el7.icinga
icinga-php-library.noarch              0.13.0-1.el7
icinga-php-thirdparty.noarch           0.12.0-1.el7
icingacli.noarch                       2.12.0-1.el7

**Comment by scriptkiddy666** [comment]
@gbin2265
Adjusting the CompatHost.php works for me as well.
But I had a look at the two files (CompatService and CompatHost) before and after the update and at least this part was never in the CompatHost.php.
(And both files only changed a little bit during the update.)

**Comment by nilmerg** [comment]
Hi,

please share the `action_url` (specifically the part with the macros) of the host in question.

**Comment by gbin2265** [comment]
Hello, 

I open the tactical view, click on the hosts, select a host -> error in the host detail

This is the url for the detail of the host  : /icingaweb2/icingadb/host?name=xxx_host_object

**Comment by gbin2265** [comment]
Hello, 

I work full icingadb and monitoring is disabled.

After some searching I thought the '**hasInstalled**' should be replaced by '**hasEnabled**' in the file modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php

From : 
$monitoringInstalled = Icinga::app()->getModuleManager()->**hasInstalled**('monitoring');
(yes monitoring is installed)
To :
$monitoringInstalled = Icinga::app()->getModuleManager()->**hasEnabled**('monitoring');
(but monitoring is disabled)


But my knowledge of PHP and icinga is far too limited for this.

**Comment by nilmerg** [comment]
> it he will always use $this->compatObject() because the module monitoring exist
> (even if it is disabled, because I only work with the module icingadb)

That's intended.
