### ISSUE TITLE
Protected custom vars not obfuscated

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingadb-web#911]
## Describe the bug
The docs state this:

> Protected Customvars[¶](https://icinga.com/docs/icinga-db-web/latest/doc/10-Migration/#protected-customvars)
> The rules previously configured at Configuration -> Modules -> monitoring -> Security have moved into the roles configuration as a new restriction. This is called icingadb/protect/variables and accepts the same rules. Just copy them over.

I can't get this to work.
## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Created a role "generic-role"
2. put `*pw*,*pass*,community,*secret*,*key*,*auth*,*token*,*user*,*id*,azure_client_subscription` into the icingadb/protect/variables field
3. import role into my Administrator and other roles
4. still see the contents of the variables

## Expected behavior
Variable contents are obfuscated by ***
## Screenshots
![image](https://github.com/Icinga/icingadb-web/assets/24474580/5d7b4885-3e33-4e52-acdf-9d291da588e2)
![image](https://github.com/Icinga/icingadb-web/assets/24474580/ef370a66-98e0-406f-8a58-93c55c991f0d)
![image](https://github.com/Icinga/icingadb-web/assets/24474580/af599f9e-0342-4fc0-8fc4-56ec212fa935)

Same string/content works in the `monitoring-module` webinterface: 
![image](https://github.com/Icinga/icingadb-web/assets/24474580/18cbc58a-792e-4c18-81dd-5a693a7a9df8)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): v1.1.0
* Icinga Web 2 version (System - About): v2.12.
* Web browser: Vivaldi, Chrome, Firefox
* Icinga 2 version (`icinga2 --version`): 2.14.0
* Icinga DB version (`icingadb --version`): v1.1.1
* PHP version used (`php --version`): 7.2.24
* Server operating system and version: rhel8

**Comment by yhabteab** [comment]
Thanks for reporting! That's a bug introduced with https://github.com/Icinga/icingadb-web/pull/779/files#diff-b0ca0479f9abe1004fecebcedba6d000307a8b4bc5192e54fd53487b0a52b125R126-R129
