### ISSUE TITLE
GrapherHook

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#92]
## Is your feature request related to a problem? Please describe.
Icinga Web 2 already provides a hook for graphers. Though this hook is ancient and does not provide the same feature-set as the monitoring module's detailview extension.

## Describe the solution you'd like
We should not carry this with us in Icinga DB Web. We should provide our own grapher hook that also allows full style and layout customizations and provides some convenience methods.

**Comment by friesoft** [comment]
I don't know if this is relevant here, but for embedded graphs (e.g. using the grafana module) it would be needed to disable refreshing of the graphing part to enable usage of iframe mode without reloading the iframe every x seconds (see https://github.com/Icinga/icingaweb2/issues/2820)

**Comment by nilmerg** [comment]
As mentioned over there, this should be a part of the grafana module. It's the module which places the iframes after all, so it should also be able to prevent Icinga Web 2 from refreshing them.
