### ISSUE TITLE
Stop dynamic check statistics if checks are disabled

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingadb-web#930]
## Describe the bug
The dynamic check statistic bar continues to move even if I disable active checks. When disabling active check + passive checks the widget gets greyed out, however the bar still moves.

## To Reproduce
* Open the detail view of a host/service
* Disable active checks -> dynamic bar keeps on moving
* Additionally disable passive checks -> check statistics widgets becomes grey, bar keeps on moving

## Expected behavior
I would expect the dynamic bar to freeze and additional indicators in the check statistics widget that visualize that there are no active checks being run.  

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.0
* Icinga Web 2 version (System - About): 2.12.0

**Comment by nilmerg** [comment]
If only active checks are disabled, the bar is animated by intention. The results are still expected to arrive at a specific interval after all. Though, if passive checks are also disabled, the animation should stop.
