### ISSUE TITLE
Using OR operator in Problem search shows hint link which doesn't work with IcingaDB enabled

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icingadb-web#931]
## Describe the bug
Creating a query for hosts or services in the Problems tab and using the | operator shows a hint link in the upper right corner, asking whether I'm missing entries. Clicking on the link creates an error. This happens in an environment where we only have IcingaDB enabled. The old monitoring module is disabled.

## To Reproduce
1. Go to Problems --> either Host or Service Problems
2. Create a query with the | operator
3. Click on the link that appears in the upper right corner of the window

## Expected behavior
The hint shouldn't appear (I understand it's part of the recent change with the ~ operator, but the hint also appears when using any other operator)

## Screenshots
An example query; note that the hint pops up with any other operator besides the ~ as well!
![grafik](https://github.com/Icinga/icingadb-web/assets/84782250/56697ce2-a5fc-4543-a3b4-4c1671d19e27)

Error message including the URL; note that the parentheses only show up after clicking the hint link
![grafik](https://github.com/Icinga/icingadb-web/assets/84782250/1629f20e-91e1-4f49-9d7c-26c07aa7bb84)

Without the parentheses, the URL works fine btw, but still shows the hint link; clicking it sends me back to the error page.
![grafik](https://github.com/Icinga/icingadb-web/assets/84782250/a004ffbd-3380-4585-b892-796f3f4722d0)

## Your Environment
![grafik](https://github.com/Icinga/icingadb-web/assets/84782250/e2a288c4-1bc6-4a9b-a578-a6709d1e68f2)

**Comment by nilmerg** [comment]
Thanks for opening the issue! I was able to reproduce it. And even better, it's already fixed as part of #927!
