### ISSUE TITLE
Force check now (redis flushall for one record)

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingadb-web#938]
## Describe the bug
I sometimes have a bad experience that the Redis does not have the same information as the database
(seeing what is different in the source/api and what is really in the database)

The worst experience i have especially with Acknowledge and Downtime.
I have already done a FLUSHALL on both masters but the problems come back.

I have the impression, but cannot yet prove, that during the icinga reload records-fields are reset in the database to the default but not in the redis.
! We don't have a director and load the config from disk - icinga2 daemon --validate --dump-objects && systemctl reload icinga2.

## Question
Currently there is a '**check now**' that will do a check but will not make any modifications ,i think, if nothing changes in the Redis.
Isn't there the option (even if it was only on the BULK screen) to create an extra button '**FORCE check now**' 
that will delete everything in the Redis (FLUSHALL for one record), read everything from the database again and then do the 'check now'
and do this for the host/service for which you are requesting a check. 

## Your Environment
icinga2.x86_64                         2.14.0-1.el7
icingadb.x86_64                        icingadb-1.1.1-1.el7
icingadb-redis.x86_64                  7.0.12-1.el7

icingaweb2.noarch                      2.12.1-1.el7
icingadb-web.noarch                    1.1.1-1.el7

**Comment by nilmerg** [comment]
This sounds more like a thing for Icinga DB itself. @julianbrost Please step in.

**Comment by julianbrost** [comment]
I have a hard time following, could you please be more precise in what exactly goes out of sync and in which way, like is it outdated?

> I have already done a FLUSHALL on both masters but the problems come back.

After all, Icinga 2 is the source of that information, so that sounds like the state within Icinga 2 is not what you expect it to be.

> I have the impression, but cannot yet prove, that during the icinga reload records-fields are reset in the database to the default but not in the redis.

The MySQL/MariaDB/PostgreSQL database used by Icinga DB is only populated with information from Redis, so if it's in that database, it must have been in Redis at some time before.

**Comment by gbin2265** [comment]
Hello,

see here information 

## Version

Icinga
icinga2.x86_64                         2.14.0-1.el7
icingadb.x86_64                        1.1.1+3.gc20f066-1692396198.el7
icingadb-redis.x86_64                  7.0.5-0.20230818.1803.el7.icinga
icingadb-web.noarch                    1.0.2+162.g3aedcca-1692399808.el7
icingaweb2.noarch                      2.11.4+124.g4ccebb78b-1691186619.el7

Postgres Enterprise database (EDB)
edb-as14-server.x86_64                 14.8.0-1.el8   



## Procedure FLUSHALL
Step 1: 
master 1 :  systemctl stop icinga2 icingadb
master 2 :  systemctl stop icinga2 icingadb
Step 2: 
master 1 : icingadb-redis-cli flushall
master 2 : icingadb-redis-cli flushall
Step 3: 
master 1 :  systemctl start icinga2 icingadb
master 2 :  systemctl start icinga2 icingadb

**Comment by gbin2265** [comment]
See an example here


## API info now today 12dec2023

If i ask info via the Source Page

**_master 1 :_** 
Object Attributes
acknowledgement	1
acknowledgement_expiry	n. a.
acknowledgement_last_change	2023-06-27T14:33:50.189+00:00

Volatile State Details
is_acknowledged	1


**_Master 2 :_** 
Object Attributes
acknowledgement	0                                  ???????????????
acknowledgement_expiry	 n. a.
acknowledgement_last_change	 n. a.
action_url	n. a.

Volatile State Details
is_acknowledged	1

**Comment by gbin2265** [comment]
## History of the <host_object> that I now use as example

24May2023 Acknowledgement cleared
27Jun2023 Acknowledgement set
22Nov2023 Soft state changed
22Nov2023 Hard State changed
30Nov2023 Downtime started


## Database acknowledgement history 
I see these info in the DB for the <host_object>
set_time=1684948478890 Wednesday 24 May 2023 17:14:38.890 comment=text  clear_time=1685540368164 (Wednesday 31 May 2023 13:39:28.164)
set_time=1687876430166 Tuesday 27 June 2023 14:33:50.166  comment=text  clear_time=[NULL]

**Comment by gbin2265** [comment]
## Check ACK on master 1, 2 and the DB

**_30nov2023_**
Master 01 : <host_object>  ACK = 1   -> Ack is 1
Master 02 : <host_object>  ACK = 0
Postgresql: <host_object>  ACK = 0   -> Ack is 0 in the DB and normaly (if you see in the history) is the ACK active from 27Jun

I do FLUSHALL on 3dec2023. ALL the ACK is now the same as the DB i think  (last line was ACK = 0)

**_12Dec2023_**
Master 01 : <host_object> ACK = 1
Master 02 : <host_object> ACK = 0
Postgresql: <host_object> ACK = 1   -> Now is the ACK 1 ?

**Comment by gbin2265** [comment]
## Host screen 
There is the button '**Remove acknowledgement**'

On the '**Comments**' he say's
**No comments created**        -> Why is the comments empty when there is text



## Question
On November 30, the ACK is at 0 for no reason
On December 12, the ACK is back again 1

Is there something in icingadb that resets the DB/REDIS to 1 based on the ACK history?
And only the ACTIVE REDIS is doing that ?

**Comment by gbin2265** [comment]
Hello,

I have had to delete and recreate more than 100 Host and 300 Service acknowledge's one by one.

I tried to remove the acknowledge on the icingaweb2 that was connected to the master, but that didn't work.
(may even click the remove link several times, but had no effect)

I then started the icingaweb2 on the endpoint from the host/service.
I was able to delete the acknowledge on the endpoint and automatically it delete also the acknowledge on the master.

For some reason something went wrong with the syncro from the master to the endpoint
I did other tests of acknowledges on the master and it immediately it synced the acknowledge to the endpoint.

The feeling was sometimes that I tried to delete the acknowledge on the master, but the endpoint automatically recreated it on the master.
But I keep saying it, this was the feeling but I cannot prove it based on log files, etc...

But you never know that someone will report this again and you can then say 'there was someone else who also had that problem'.


I hope that in the next few days I will see that the problem does not return.

I'm going to leave the case open for another 2 weeks, and if nothing else has happened, I'll close it.

**Comment by gbin2265** [comment]
Hello,

After deleting and recreating all the acknowledges/downtime that did not work correctly, no new problems occurred after a week.

I can only think that these were errors that came with the migration to icingadb.

I'm going to close this case and hope that I don't have any new problems in the future.

regards,
Geert
