### ISSUE TITLE
Include details about the object for which a macro could not be resolved

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingadb-web#952]
Long story short - it's a little Deja Vu of https://github.com/Icinga/icingaweb2/issues/3759 for the old monitoring module. @nilmerg fixed this for us in a short way. It would be great to have this also in  icingaweb-db. 

What I have saw only these change only this line https://github.com/Icinga/icingadb-web/blob/274b903cbe455de6c3bc67faa2ca40b829857f77/library/Icingadb/Common/Macros.php#L106 need to be changed to 
` Logger::debug('Unable to resolve macro "%s" on object "%s". An error occurred: %s', $macro, $object->name, $e);`

Because the CLA question is not clarified in our company yet, I can't make a pull request. sorry

**Comment by carraroj** [comment]
ref/NC/804864
