### ISSUE TITLE
Dashboard Migration-Tool - some parameter are not converted correctly 

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingadb-web#953]
We tested the new migration tool for dashboard from the monitoring modul to icingadb-web - wich cames with the latest version of icingaweb/icingadb-web. Basically it worked very well. But there were two parameter which wouldn't converted correctly:

e.g.
1. If there was in the filter `service_state_type=Soft`, that would be converted to `service.state.state_type=(soft|hard)`. But that throws following error:
![image](https://github.com/Icinga/icingadb-web/assets/38723488/e1680de8-77fe-4857-a2ec-7981b73b6cdb)
With a string comparision - only "sof"t or " hard" - the dashboard works

2. If somebody has the param "modifyFilter" in his filter, the dasboard doesn't work. So it looks like that the migration don't handle this (e.g. delete the param)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.1
* Icinga Web 2 version (System - About): 2.12.1
* Web browser: Firefox, Edge
* Icinga 2 version (`icinga2 --version`): 2.14.1
* Icinga DB version (`icingadb --version`): 1.1.1
* PHP version used (`php --version`): 8.0.3
* Server operating system and version: rhel 9

**Comment by carraroj** [comment]
ref/NC/804872

**Comment by nilmerg** [comment]
1. `(soft|hard)` is array syntax and completely valid. The class `ipl\Web\SearchBar\Terms` doesn't seem to handle this correctly. There may be more cases of invalid handling, so further errors should be expected.
2. The class `UrlMigrator` of Icinga DB Web is responsible for parameter handling. It needs to drop `modifyFilter` as suggested.
