### ISSUE TITLE
Unable to filter booleans

### ISSUE THREAD

**Issue by deric** [Icinga/icingadb-web#958]
## Describe the bug
I'd like to filter by `boolean` field.

## To Reproduce

The URI looks like:
```
icingadb/services?host.state.is_problem~true
```
- postgresql DB backend

## Expected behavior
Show only matching records, don't throw SQL errors. The UI shouldn't allow passing invalid values.

For `boolean` field only meaningful operators should be shown, without `>`, `<=`, etc.
![Screenshot_20240117_133113](https://github.com/Icinga/icingadb-web/assets/138573/6cb8ed63-a919-4aab-84e7-6fedb0e5c592)

and suggest or convert valid values.

## Logs 
```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input value for enum boolenum: "true"
CONTEXT: unnamed portal parameter $1 = '...'
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About):
* Icinga Web 2 version (System - About): `2.12.1`
* Icinga 2 version (`icinga2 --version`): `r2.14.1-1`
* Icinga DB version (`icingadb --version`): `v1.1.1`
* PHP version used (`php --version`): `8.2.7`

**Comment by deric** [comment]
@nilmerg Thanks, that works. But it's not very intuitive. For old version also `0` and `1` values were accepted.

**Comment by nilmerg** [comment]
We very much know this. Though, it doesn't just apply to booleans and is quite a task to do it properly. For the moment, please rely on the search bar's autocompletion (Push spacebar in empty fields to get some available options) feature to know what's correct and what's wrong.
