### ISSUE TITLE
Service / Host Actions are not shown in Icingadb-web

### ISSUE THREAD

**Issue by k3nd0x** [Icinga/icingadb-web#960]
## Describe the bug
Service / Host Actions are not shown in Icingadb-web. We have the same config active with the old Icingaweb. 

## To Reproduce
Configure host-actions or service-actions in icingadb-web.

## Expected behavior
Host / Service - urls shown like in the old versions. 

## Screenshots
Old:
![grafik](https://github.com/Icinga/icingadb-web/assets/97670834/f397e9a2-f90a-4b98-9afb-aa621b11648c)

New: 
![grafik](https://github.com/Icinga/icingadb-web/assets/97670834/4ebbd1b1-aac9-446f-a654-f546abdee5f8)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.1
* Icinga Web 2 version (System - About): 2.12.2
* Web browser: Firefox, Edge, Chrome
* Icinga 2 version (`icinga2 --version`): 2.14.2
* Icinga DB version (`icingadb --version`): v1.1.1
* PHP version used (`php --version`): 8.1.2
* Server operating system and version: Ubuntu 20.04

**Comment by nilmerg** [comment]
Hi,

did you perform the migration already? (https://icinga.com/docs/icinga-db-web/latest/doc/10-Migration/#navigation)

**Comment by k3nd0x** [comment]
Hi,
Thanks for the quick reply. Unfortunately, I missed the navigation part of the guide. Now it works, thanks :)
