### ISSUE TITLE
Filtering services not working as expected

### ISSUE THREAD

**Issue by sysadminsha** [Icinga/icingadb-web#965]
## Describe the bug
Hi

I came across this issue while filtering services by multiple conditions.

This is the query which I am using:
`host.vars.application[*]~SAS*&host.vars.application[*]!=Oracle Database`

While I get 60 hits for hosts, I retrieve an empty result for services using the same filter.
![image](https://github.com/Icinga/icingadb-web/assets/34301671/5d9eab59-1914-4634-b65a-766e800d72d1)
![image](https://github.com/Icinga/icingadb-web/assets/34301671/3de15b68-2a38-48d0-ba3d-b8f2294a1cf5)

Now when I take the SQL queries which are generated by Icinga-DB and compare them to each other, there is a difference in the services' WHERE-clause. The service query has additional LEFT JOINs. I can finally get the correct result when I replace those with RIGHT-/INNER JOINs.

This is the simplified query which is generated by Icinga-DB:
![image](https://github.com/Icinga/icingadb-web/assets/34301671/2fc3aaa3-b532-4746-9107-b87cc3568883)

And here the same query changed by me:
![image](https://github.com/Icinga/icingadb-web/assets/34301671/2ab4395d-fa3b-424c-b435-f444d95458c2)

## To Reproduce
1. Goto Overview -> Services
2. Apply a filter with at least 1 "AND"-condition which contains host variables

## Expected behavior
To see the services behind those hosts which are not filtered out.

## Screenshots
See above

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.1
* Icinga Web 2 version (System - About): 2.12.1
* Web browser: Chrome/Edge
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Icinga DB version (`icingadb --version`): v1.1.1
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: RHEL8

**Comment by nilmerg** [comment]
Hi,

seems to work fine for me without any changes:

![image](https://github.com/Icinga/icingadb-web/assets/16668527/d519edcd-1510-448c-b125-d10cd54d5e46)

```
object Host "with-fruits" {
    check_command = "dummy"
    check_interval = 5m
    retry_interval = 1m
    max_check_attempts = 5

    vars.dummy_state = 0
    vars.fruits = ["apple", "banana", "orange", "papaya"]
}

object Host "also-with-fruits" {
    check_command = "dummy"
    check_interval = 5m
    retry_interval = 1m
    max_check_attempts = 10

    vars.dummy_state = 0
    vars.fruits = ["banana", "apple", "orange"]
}
```

Please verify that the hosts you get after adjusting the query, really meet the requirements.

**Comment by nilmerg** [comment]
Eh, sorry, misread at first. But still, the service of that host is found:
![image](https://github.com/Icinga/icingadb-web/assets/16668527/d3e12e01-ddfd-4bbe-b743-69d525c68636)

**Comment by carraroj** [comment]
/ref/NC/806241

**Comment by sysadminsha** [comment]
Hi,

ok. I random picked 3 services from the result and I can verify that the adjusted query indeed meet the requirements.

![2024-01-29 15_15_00-WinSSHTerm](https://github.com/Icinga/icingadb-web/assets/34301671/933696a4-53b5-4190-9f5b-ad8aa5a745ae)

And then I looked up the corresponding hosts
![2024-01-29 15_26_50-WinSSHTerm](https://github.com/Icinga/icingadb-web/assets/34301671/150848c4-5363-4e25-b428-3fac676b4e69)

Finally I checked that the host objects match the filter criteria
![2024-01-29 15_33_51-Icinga Web und 6 weitere Seiten - Geschäftlich – Microsoft​ Edge](https://github.com/Icinga/icingadb-web/assets/34301671/2868f452-c140-4b6a-90ae-09a9a5cd4355)
![2024-01-29 15_44_04-Icinga Web und 6 weitere Seiten - Geschäftlich – Microsoft​ Edge](https://github.com/Icinga/icingadb-web/assets/34301671/d3657ed6-2062-4868-8cb8-91b46b19f632)
![2024-01-29 15_47_35-Icinga Web und 6 weitere Seiten - Geschäftlich – Microsoft​ Edge](https://github.com/Icinga/icingadb-web/assets/34301671/ea801bcc-907b-43a8-b028-ade6389384ef)

**Comment by mj84** [comment]
I'm also seeing some strange behavior while trying to restrict access to hosts and services.

I'm running a freshly installed Icinga2 2.14.2, Icingaweb2 2.12.1, IcingaDB 1.1.1 and IcingaDB-Web 1.1.1 on Debian Bookworm with PHP 8.2.7.

We are also using Arrays in the Host objects which contain strings and based upon the presence of some strings, hosts (and their services) should be filtered out for some users, for example:

```
vars.tags = [
  "invisible" // used to hide objects for all non-admins
]
```

Querying hosts for those who do NOT contain a certain tag works fine:
![image](https://github.com/Icinga/icingadb-web/assets/12526366/4b242f0c-9903-4959-bb60-1877d0b7583c)

When using the exact same query for services, I receive zero results:
![image](https://github.com/Icinga/icingadb-web/assets/12526366/8764e029-545b-40d1-b38c-3034575fef49)

The IcingaDB query in both cases is expanded to these URL parameters: `?host.vars.tags%5B%2A%5D!=invisible`

**Comment by mj84** [comment]
On a side note:
I have experimented a bit with the queries and it seems to me, that the negating query for
 `host.vars.tags[*]=something` (meaning: vars.tags contains "something") 
should not be `host.vars.tags[*]!=something` but rather `!(host.vars.tags[*]=something)`.

Also, I am seeing different behavior depending on the tag value I filter for.
The tag value "invisible" is problematic, but "invi_sible" is not, at least in my case using PostgreSQL.

Currently it seems to me that I receive the desired behaviour by using the form `!(host.vars.tags[*]=some_value)` and making sure to include an underscore in the value.

**Comment by nilmerg** [comment]
@mj84 This is an already acknowledged bug: #865

@sysadminsha After some struggling and debugging, I've reproduced it. The catch was, that I needed a host that has the custom variable you don't want (Oracle Database) but without any services attached to it. This is directly related with #974 as it's caused by the same bug. The good news is, it's easy to fix, just not easy to find :sweat_smile:
