### ISSUE TITLE
Cancelling multiple downtimes looks bad

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb-web#97]
## Describe the bug
![Bildschirmfoto von 2020-05-27 10-08-13](https://user-images.githubusercontent.com/16668527/82994225-1a4f3a00-a002-11ea-8b3e-3bf4eab5371d.png)

## Your Environment
master, nuff said

**Comment by flourish86** [comment]
Same for comments.

![Screenshot 2020-07-28 at 10 17 16](https://user-images.githubusercontent.com/6977434/88638246-852cf800-d0bb-11ea-9108-fd3911390214.png)

**Comment by nilmerg** [comment]
Will be resolved once we drop the dependency to the monitoring module.
