### ISSUE TITLE
Expiring non-ack comment displayed as ack comment

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingadb-web#98]
## Describe the bug

A non-ack comment with an expiration time is displayed as ack comment.

## To Reproduce

1. Add a non-ack comment with an expiration time.
2. Wait for it to appear in the detail view.
3. Click on it.

## Expected behavior

It's displayed as non-ack comment.

## Screenshots

<img width="1264" alt="Bildschirmfoto 2020-05-27 um 14 22 26" src="https://user-images.githubusercontent.com/6053266/83018809-2d740100-a026-11ea-89b8-c89a02215998.png">

## Your Environment

* Icinga DB Web version (System - About): master
* Icinga Web 2 version (System - About): Icinga/icingaweb2#4162
* Web browser: Opera
* Icinga 2 version (`icinga2 --version`): Icinga/icinga2#8035
* Icinga DB version (`icingadb --version`): master
* PHP version used (`php --version`): 7.3
* Server operating system and version: CentOS 7

## Additional context

Was about to introduce Icinga/icingaweb2#4162 here, too, but realized... you don't seriously depend on the monitoring mod?!

**Comment by nilmerg** [comment]
Working for me in master.
